### ISSUE TITLE
File Restructure

### ISSUE THREAD

**Issue by FrederickChan** [Catzenjaeger/FigureLib_4#101]
There is 2 locale files in Figurelibs. We'll just use one.

**Comment by FrederickChan** [comment]
Nvm, since your environment is good, let's not change anything. We'll just fix the bugs.

**Comment by Catzenjaeger** [comment]
:) you mean the locales in panels right ... yes i dont know why i do that :)

**Comment by FrederickChan** [comment]
Your server is now updating on files from my other PC. 

I see textarea and the datepicker is now back.

**Comment by Catzenjaeger** [comment]
cool :100:

**Comment by Catzenjaeger** [comment]
waittttttttttttttttttttt .. 

you ftp rights is for /site
on site figurelib not installed right? 

i hope we had not a missunderstanding here

atm: 
/live (newest php fuion from yesterday but with many errors and no popup and datapicker)
/site (newest php fusion but NO figurelib installed .. right?

**Comment by Catzenjaeger** [comment]
ok in have checked /live

-> admin area --> button forum ranks goes to home site
-> admin area --> user Fields goes to home site 
-> submit figurelib -> no popup image upload
-> submit figurelib -> no data picker

**Comment by Catzenjaeger** [comment]
[1.zip](https://github.com/Catzenjaeger/FigureLib_4/files/456533/1.zip)

**Comment by FrederickChan** [comment]
Fixed.

**Comment by FrederickChan** [comment]
These are figurelib's stuff, we do after core system all ok:

-> submit figurelib -> no popup image upload
-> submit figurelib -> no data picker
-> submit figurelib -> no coma in currency field possible
-> figurelib/admin.php -> section=figurelib_form&action=edit -> no popup image upload
-> figurelib/admin.php -> section=figurelib_form&action=edit -> no data picker
-> figurelib/admin.php -> section=figurelib_form&action=edit -> different length of fields (all set width 520 but it would be ignored by system)
-> figurelib/admin.php -> section=figurelib_form&action=edit -> no coma in currency field possible

**Comment by FrederickChan** [comment]
Other core faults? Anywhere?

**Comment by Catzenjaeger** [comment]
hmn in Artemis Admin Theme i dont see aw/glphos

**Comment by FrederickChan** [comment]
![capture](https://cloud.githubusercontent.com/assets/4078041/18271479/da6ef4f6-7464-11e6-980a-7a11c0bbc508.JPG)

**Comment by Catzenjaeger** [comment]
in news settings admin are i get this:
#0 redirect(../../) called at [/var/www/vhosts/aliencollectors.com/httpdocs/live/includes/core_functions_include.php:973] #1 pageAccess(S8) called at [/var/www/vhosts/aliencollectors.com/httpdocs/live/infusions/news/classes/admin/controllers/news_settings.php:35] #2 PHPFusion\News\NewsSettingsAdmin->displayNewsAdmin() called at [/var/www/vhosts/aliencollectors.com/httpdocs/live/infusions/news/classes/admin/news_admin_view.php:88] #3 PHPFusion\News\NewsAdminView->display_admin() called at [/var/www/vhosts/aliencollectors.com/httpdocs/live/infusions/news/news_admin.php:22] redirected to ../../

**Comment by FrederickChan** [comment]
![capture](https://cloud.githubusercontent.com/assets/4078041/18271498/fda4011e-7464-11e6-9c0a-a32ca9b25ac1.JPG)

**Comment by FrederickChan** [comment]
Yes, i am currently asking redirect to not redirect and to show me which line calls redirect so I can go to that page and make adjustments.

**Comment by FrederickChan** [comment]
![capture](https://cloud.githubusercontent.com/assets/4078041/18271563/53023cf2-7465-11e6-8278-a57b2eebde94.JPG)

**Comment by FrederickChan** [comment]
Now i turned it off, reuploaded off

**Comment by Catzenjaeger** [comment]
:) super. system looks good atm

**Comment by FrederickChan** [comment]
Ok, so now...

-> submit figurelib -> no popup image upload
-> submit figurelib -> no data picker
-> submit figurelib -> no coma in currency field possible
-> figurelib/admin.php -> section=figurelib_form&action=edit -> no popup image upload
-> figurelib/admin.php -> section=figurelib_form&action=edit -> no data picker
-> figurelib/admin.php -> section=figurelib_form&action=edit -> different length of fields (all set width 520 but it would be ignored by system)

Leave these to me. I'll get it done.


--- This one not yet, Defender doesn't support currency type validation yet 
-> figurelib/admin.php -> section=figurelib_form&action=edit -> no coma in currency field possible

**Comment by Catzenjaeger** [comment]
ok ok :)

**Comment by FrederickChan** [comment]
Width 520px fixed.

**Comment by FrederickChan** [comment]
i will take leave until 5hours later. gotta attend to kids.

**Comment by Catzenjaeger** [comment]
:)

**Comment by FrederickChan** [comment]
Take anything you want to do. I don't think I can work on anything tonight. Tomorrow I'll see to the rest of  the issues. Please check what you can do and solve it first. I'll take remaining tomorrow.

**Comment by FrederickChan** [comment]
-> submit figurelib -> no popup image upload
-> submit figurelib -> no data picker
-> submit figurelib -> no coma in currency field possible
-> figurelib/admin.php -> section=figurelib_form&action=edit -> no popup image upload
-> figurelib/admin.php -> section=figurelib_form&action=edit -> no data picker

remaining.

**Comment by Catzenjaeger** [comment]
no date picker & popup solved --> PHP F development team have change the names of dynamic files in folder!

**Comment by Catzenjaeger** [comment]
- [ ] -> submit figurelib -> no popup image upload
- [ ] -> submit figurelib -> no data picker
- [ ] -> submit figurelib -> no coma in currency field possible
- [ ] -> figurelib/admin.php -> section=figurelib_form&action=edit -> no popup image upload
- [ ] -> figurelib/admin.php -> section=figurelib_form&action=edit -> no data picker
- [ ] -> submit figurelib -> field lengh different all set 100% but different

**Comment by Catzenjaeger** [comment]
so, this list is uptodate. All open points see above
