### ISSUE TITLE
live/maincore.php --> strlen() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#103]
live/maincore.php
/live/infusions/figurelib/admin.php?aid=74d5d06d7076c78d&section=figurelib_form&action=edit&figure_id=15
strlen() expects parameter 1 to be string, array given
Line: 236

Non fatal Runtime Errors 	
live/maincore.php
/live/infusions/figurelib/admin.php?aid=74d5d06d7076c78d&section=figurelib_form&action=edit&figure_id=16
strlen() expects parameter 1 to be string, array given
Line: 236

**Comment by Catzenjaeger** [comment]
some some like this: https://github.com/Catzenjaeger/FigureLib_4/issues/97

**Comment by FrederickChan** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/ac182749a247b720de591b33435c705aa7dd863a

**Comment by Catzenjaeger** [comment]
no sorry it was not the solution i get this error again and again

live/maincore.php
/live/infusions/figurelib/admin.php?aid=e45dcab2f5db75e1&section=figurelib_form&action=edit&figure_id=16
pathinfo() expects parameter 1 to be string, array given
Line: 237
