### ISSUE TITLE
Server Mantainence /live/ - Custom Files & Reports.

### ISSUE THREAD

**Issue by FrederickChan** [Catzenjaeger/FigureLib_4#108]
Please make it a habit not to touch any of the 'repository files'. It's hard to update. It's a hard lesson myself too, so many bad experience.
 
Instead you should create a new file so when upload full, you don't replace code.

I've just replaced some files - now got some locale error. Please make new files and get the locale in like this.

$locale = fusion_get_locale('', PATH_TO_SOME_FILE);
$locale += fusion_get_locale('', PATH_TO_SOME_FILE2);
.. keep adding

**Comment by FrederickChan** [comment]
Forum Is updated.

Now checking jquery comments.

**Comment by FrederickChan** [comment]
Comments latest is uploaded. http://aliencollectors.com/live/infusions/news/news.php?readmore=4#edit_comment

Comments administration is uploaded.

Improper and outdate BBCodes removed. Do not ever use them until they are fixed.

**Comment by FrederickChan** [comment]
Custom page is 100% working. http://aliencollectors.com/live/viewpage.php?page_id=3
Added a comments widget. It's running jquery.

**Comment by FrederickChan** [comment]
Ok, so far nothing is crashing anymore. Please stop syncing with Main repository now. Final version is 4.5 I think is good enough.

Your site is ready to launch as is.  

Thank you.

**Comment by Catzenjaeger** [comment]
ok thanx
