### ISSUE TITLE
MASSIVE ERROR - page nav - on all sites wrong - 

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#109]
Settings: 

4 figures per line
12 figures per site

but i get when have 5 figures in a category a page nav for site 2 ... thats wrong
when i click on it comes a error message "not figures"

how can i fix this fast / or what is wrong

its important  .. thanx

![ashampoo_snap_2016 09 11_15h39m40s_005_](https://cloud.githubusercontent.com/assets/19621858/18417656/5ba8491c-7836-11e6-806e-1e6dc4e301da.jpg)

**Comment by FrederickChan** [comment]
Give me your makepagenav() implementations 

Show me your codes:
1. ALL ROWS count 
2. Your Limit per Page
3. Your current fetched rows 
4. Your Link.

And tell me what is 'wrong' mean? Link error or count error?

**Comment by FrederickChan** [comment]
````

/**
 * Making Page Navigation
 * @global array $locale
 * @param int    $start The number of the first listed item - $_GET['rowstart']
 * @param int    $count The number of displayed items - LIMIT on sql
 * @param int    $total The number of all items - a dbcount of total
 * @param int    $range The number of links before and after the current page
 * @param string $link The base url before the appended part
 * @param string $getname the variable name in the query string which stores
 *                            the number of the current page
 * @return boolean|string FALSE if $count is invalid
 */
function makepagenav($start, $count, $total, $range = 0, $link = "", $getname = "rowstart", $single_button = FALSE) {
````

**Comment by Catzenjaeger** [comment]
my page nav is shown but someone is wrong well i become to show a site 2 with the next 12 figures but this is wrong well i have less than 12 figures and not more. normally the site is shown when i have more than 12. This is wrong

my settings are:
4 figures per line
12 figures per site

atm i have 5 figures and become a site 2!! When i click on site 2 button i get a message that i have no figures in this category. Someone is wrong but i dont not what

my code: 
core file (figures.php) --> https://github.com/Catzenjaeger/FigureLib_4/blob/master/infusions/figurelib/figures.php
template --> https://github.com/Catzenjaeger/FigureLib_4/blob/master/infusions/figurelib/templates/template_render_figure_items.php

**Comment by Catzenjaeger** [comment]
solved
