### ISSUE TITLE
Error: "Show figure on page" in Admin Menue 

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#11]
without function changes will not write in DB

**Comment by Catzenjaeger** [comment]
this field doesnt work too

- Show comments? *
- Show ratings *

**Comment by Catzenjaeger** [comment]
Hier stimmt einiges nicht. Die Checkboxes 

"figure_allow_comments" und Checkbox "figure_allow_rastings" dürften doch eigentlich gar kein Required = TRUE haben ... oder? 

weiterhin

figure allow coment und rating ist global für alle Figuren in den Settings ein/ausschaltbar 
ABER auch pro Figur .. ....das kann man im Editbereich einer einzelnen Figur tun.

das hatte eigentlich immer funktioniert aber jetzt nicht mehr. Da sind sicher einige Fehler din. Habs probiert aber nach ner Stunde frustriert aufgeben 

File: https://github.com/Catzenjaeger/FigureLib_4/blob/master/infusions/figurelib/admin/admin_figurelib.php

**Comment by DavidGuetl** [comment]
# fixed
