### ISSUE TITLE
ToDo: alignment in panels

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#13]
in all panels we have a ugly alignment about the images. 
Sure we can change that with a div but give it a better solution? well when we change the image sizes later, so we have to change all files again

![ashampoo_snap_2016 08 20_18h39m06s_040_](https://cloud.githubusercontent.com/assets/19621858/17832532/67bc6dec-6705-11e6-9248-dbf0111a6a0c.jpg)

**Comment by DavidGuetl** [comment]
Merge with #16 ?
