### ISSUE TITLE
ToDo: FIX needed

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#15]
some code its from a older version of code.
 Now we have the numbers of items in settings. ($max_image_allowed = $asettings['figure_image_upload_count'];) 
Guess the last row is not correct now

i mean this: 'deactivate' => $image_count > 10 ? true : false,

`	$max_image_allowed = $asettings['figure_image_upload_count'];
    $image_count = dbcount("(figure_images_image_id)", DB_FIGURE_IMAGES, "figure_images_figure_id='$figure_id'");
	
    $file_input_options = array(
        "inline" => TRUE,
        "template" => "modern",
        "multiple" => TRUE,
        "upload_path" => INFUSIONS."figurelib/figures/images/",
        "required" => FALSE,
        "max_byte" => $asettings['figure_photo_max_b'],
        "max_count" => $max_image_allowed - $image_count+1,
        'max_width' => $asettings['figure_photo_max_w'],
        'max_height' => $asettings['figure_photo_max_h'],
        // set thumbnail
        'thumbnail' => 1,
        'thumbnail_w' => $asettings['figure_thumb_w'],
        'thumbnail_h' => $asettings['figure_thumb_h'],
        "thumbnail_folder" => "thumbs/",
        'delete_original' => 0,
        'type' => 'image',
        'ext_tip' => sprintf($locale['figure_035'], parsebytesize($asettings['figure_photo_max_b']) . $locale['figure_036'] . $max_image_allowed),
        'deactivate' => $image_count > 10 ? true : false,
    );`

**Comment by DavidGuetl** [comment]
'deactivate' => $image_count > $max_image_allowed ? true : false,

**Comment by Catzenjaeger** [comment]
ok change it -- have to test now

**Comment by Catzenjaeger** [comment]
closes file updated on github -- thanx Master of the codes :)
