### ISSUE TITLE
Question: Image size in figurelib -- where?

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#16]
im Moment habe ich noch Bauchschmerzen was das Layout der panele angeht. Die Bilder sind alle unterschiedlich und das sieht nicht schön aus. Hast du eine Idee wie man besser machen könne?

**Comment by DavidGuetl** [comment]
Gib den Bildern einfach eine fixe Höhe mit height und die Breite lass sich selbst bestimmen

**Comment by Catzenjaeger** [comment]
nun ja aber dann brechen aber die Zeilen um ... heisst man muss auch den div code dazu immer entsprechend anpassen. Außerdem sind die Bilder alle in diversen Formaten. Das sieht unschön aus. Gifs sollten nicht abgespielt werden das sieht doof aus.

**Comment by DavidGuetl** [comment]
2.ten Thumb in grösse von 40px mal 40px oder so?

**Comment by Catzenjaeger** [comment]
war ursprünglich drin aber der code ist dann umgebaut worden.  momentan ist 300x400 eingestellt also in den settings

**Comment by DavidGuetl** [comment]
Ggf. Wieder einbauen?

**Comment by Catzenjaeger** [comment]
war kompliziert und hatte nicht gefunzt. ahtte irgendwie nicht gespeichert

**Comment by DavidGuetl** [comment]
Schließbar -> Fehlerbehebung auf der Testseite bereits.
