### ISSUE TITLE
Question: Link zusammensetzen

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#19]
Ich würde gerne ein Videobereich mit einbauen

prinzipell funzt das ... da ich aber den embded code variabel gestalten muss wollte ich das zusammenbauen. 

Teil 1 die url bis dahin wo der embded code kommt
Teil 2 dann der eigentliche code den der user dann später eingeben soll (somit ist der link immer gleich)

Problem wäre nur wenn er das video nicht von tube hat .. aber dort gibt es numla die meisten. Bootstrap bieetet einen easy code zum einbinden

das ganze sieht so aus funzt aber nicht

```
$embedcode = "49p2cglZn9Q"; (kommt später aus DB)
							
echo "<div align='center' class='embed-responsive embed-responsive-16by9' >
	<iframe class='embed-responsive-item'  src='https://www.youtube.com/embed/'".$embedcode."'></iframe></div>";
```

wenn ich aber so mache gehts: 

```
echo "<div align='center' class='embed-responsive embed-responsive-16by9' >
	<iframe class='embed-responsive-item'  src='https://www.youtube.com/embed/49p2cglZn9Q'></iframe></div>";
```

weißt du zufällig was falsch ist?

**Comment by DavidGuetl** [comment]
Vor ".$embedcode ist ein ' zuviel :-)

**Comment by Catzenjaeger** [comment]
GEHT TROTZDEM NICHT HABE ALLES PROBIERT

& und auch ?

**Comment by Catzenjaeger** [comment]
done -- funzt alles ... lagh an was anderes . :)
