### ISSUE TITLE
E-mail notification on submit

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#2]
David you send "Neue Figur" with png but I just got no email ;(

**Comment by DavidGuetl** [comment]
Can you submit a Figure pls?

**Comment by DavidGuetl** [comment]
![figure](https://cloud.githubusercontent.com/assets/19527428/17831716/e9f188c0-66f0-11e6-833f-99c3c2b90eb3.png)

**Comment by Catzenjaeger** [comment]
hmnnn i have mo mail in spam
damn what is it ok i have to test again
guess its a fault by me

**Comment by Catzenjaeger** [comment]
works :+1:
