### ISSUE TITLE
Idea: Dropdown with Länderauswahl

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#20]
momentan werden die Freihand eingetragen.

**Comment by DavidGuetl** [comment]
Eher ein kleines Problem!

Man suche in der submit.php und weiteren Einsendedatein folgendes:
```
// Text Field "Country"
		echo form_text("figure_country", $locale['figure_436'], $submitdata['figure_country'],
			array(
				"inline" => TRUE,
				"max_length" => 100,
				"width" => "400px",
				"placeholder" => $locale['figure_1804']
			)
		);
```

Man ersetzte dieses durch:
```
// Country Field
		$countries = array();
		require_once INCLUDES."geomap/geomap.inc.php";
		echo form_select("figure_country", $locale['figure_436'], $submitdata['figure_country'], [
			"options" => $countries,
			"inline" => true,
			"width" => "400px",
			"placeholder" => $locale['figure_1804'],
			"allowclear" => true
		]);
```

Ein auslesen könnte ich mir so vorstellen, ist aber ungetestet:
```
require_once INCLUDES."geomap/geomap.inc.php";
if (isset($countries[$data['figure_country']])) {
  echo $countries[$data['figure_country']];
} else {
  echo "We don't know this Country!";
}
```

**Comment by Catzenjaeger** [comment]
leider nicht habe beides eingebaut in die submit. es erschein ein grau unterlegtes feld und darüber die schrift ... kenne das land nicht

**Comment by DavidGuetl** [comment]
Dieser Text wird beim auslösen benötigt, zb. figures.php

```
require_once INCLUDES."geomap/geomap.inc.php";
if (isset($countries[$data['figure_country']])) {
  echo $countries[$data['figure_country']];
} else {
  echo "We don't know this Country!";
}
```

der obere Code gehört in die submit.php

**Comment by Catzenjaeger** [comment]
ich habe nur das obere eingebaut ... feld ist nicht beschreibbar .. ist grau unterlegt
fehlt ne globale defintion weil der muss ja $countries irgendwo herholen

**Comment by Catzenjaeger** [comment]
Das funzt :) 
welche files müssen noch geändert werden? Im Adminbereich gibts ja auch ein formular.

was macht man eigentich wenn man das land nicht weis? es gibt ja dort kein "Unkonwn"

**Comment by DavidGuetl** [comment]
```
		// Selectlist: Country Field
        $countries = array();
        require_once INCLUDES."geomap/geomap.inc.php";
		$countries = array_merge(["Unknown"], $countries);
        echo form_select("figure_country", $locale['figure_436'], $submitdata['figure_country'], [
            "options" => $countries,
            "inline" => true,
            "width" => "400px",
            "placeholder" => $locale['figure_1804'],
            "allowclear" => true
        ]);
```

Dann wäre Option "Unknown" dabei.

Ja Adminformular.

Und halt überall wo ein Land ausgegeben wird (Code 3)

**Comment by Catzenjaeger** [comment]
hmnn stop ... du bist zu schnell: 

also was muss ich genau jetzt machen :+1: 
das hier
require_once INCLUDES."geomap/geomap.inc.php";
if (isset($countries[$data['figure_country']])) {
  echo $countries[$data['figure_country']];
} else {
  echo "We don't know this Country!";
}

oben in die figure.php

was noch? 
den Eingabecode für das feld in die admin_figurelib.php datei auch reinpacken und dort müsste ja der obere code auch rein weil dort wird ja die Datei editiert und dargestellt ... also auch ausgelesen

**Comment by DavidGuetl** [comment]
Nein Nein ..

Die Auslesung muss direkt dort hin wo ausgelesen wird.

**Comment by Catzenjaeger** [comment]
ich bin gerade voll überfordert 
die admin_figurelib.php muss eh überarbeitet eerden da ja dort die checkfields nicht gehen
kann du da mal reinschauen bitte .. in diesen Zuge kann man diese sachen auch gleich einbauen :)

ich machs auch selber musst mir nur sagen wo wie und was :)
Ich komme gar nicht hinterher so schnell bist du hier ... alle Achtung Respekt .. wie machst du das hast du 4 Bildschirme? :)

**Comment by DavidGuetl** [comment]
Also wenn gehts bei mir erst eher später :-o wenns nicht sofort sein muss^^

Hehehe wenn du wüsstest xD Aber nein sitze nur mit nen kleinen Lappy, hab aber ungefähr 40 Tabs im Browser offen und im Code Editor sicher gefühlte 30 Dateien :O

**Comment by Catzenjaeger** [comment]
also die admin_figurelib bedarf überarbeitung die funzt nicht richtig. später ist ja kein problem .. oder ist später mit viellllll später gemeint LOL

ich muss noch paar andere dinge wie zB das verlorene Settingfeld wieder einbauen .. das ist weg!! :O

**Comment by DavidGuetl** [comment]
Naja eher erst gegen Abend ..

Ja willst du auch gleich noch paar Felder einbauen? Würde betreffend den ganz kleinen Icons in Panels, MyCollection etc überall gerne wieder die Thumbs 2 einbauen - würde dir natürlich in der richtigen Issue schreiben welche Settings Felder ich brauche.

**Comment by Catzenjaeger** [comment]
was meinst du mit Felder -- wo? in der admin_figurelib?

wenn du fragst: ich habe ja Affiliate Links drin. Normalerweise sind das aber codes die Amazon bereitstellt und dann dazu einblendet. Ich weiss aber nicht wie das genau zu handeln ist und wie man es machen soll. 
Normalerweise ist es so , das Amazon dir einen Codegenerator gibt und du dann das entsprechende Produkt (hier Figur) suchst .. dann auf create gehst und man bekommt einen Link (entweder als Textlink aber meist als kleines Bildchen mit Beschreibung) 

http://www.selbstaendig-im-netz.de/2012/01/16/affiliate-marketing/amazon-make-money-monday/

Momentan habe ich das so .. das ich einen Textlink mache und diesen dann in das Feld im Formular eintrage. Ist ein Link drin wird das symbol farbig auf der figurenseite und man kann draufklicken und wird dann zum produkt geführt. 

Ich denke das ist ok so. 

allerdings arbeiten viele mit maskiereungen (aber das lass ich leiber für den moment)

was meinst du noch für andere Felder?  weisst du was richtig cool wäre ??? ein mitlaufender EDIT und DELTE Button im adminbereich. wenn man mal was schnell ändert muss man immer ewig scollen .. geht so etwas überhaupt? Das wäre mal geil

**Comment by DavidGuetl** [comment]
Kann ich dir mit einbauen, wenn ich eh die Submit komplett überarbeite ;-)

**Comment by Catzenjaeger** [comment]
ok dann kann ich das hier zumachen?

**Comment by DavidGuetl** [comment]
Jeps
