### ISSUE TITLE
Error: Guest see "no user have this figure" = its wrong

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#22]
was aber nicht stimmt --- da ist etwas falsch

so siehts aus ... müsste aber Catzenjaeger angezeigt werden da ich diese Figur i mycollection habe (siehe Bild 2)

![ashampoo_snap_2016 08 21_02h21m51s_056_](https://cloud.githubusercontent.com/assets/19621858/17834559/24d7dbba-6746-11e6-9841-4acdc8f685b9.jpg)

![ashampoo_snap_2016 08 21_02h23m24s_057_](https://cloud.githubusercontent.com/assets/19621858/17834561/43d75388-6746-11e6-999a-3fa16f3c5af0.jpg)

**Comment by Catzenjaeger** [comment]
fixed & closed . File is updated

**Comment by Catzenjaeger** [comment]
ich bekomme die Namen nicht mittig gesetzt

`if (dbrows($resultufc) != 0) {
				echo "<div align='center'>\n";
				echo $locale['userfigure_003'];		
				//echo "<p>";	
				echo "</div>";	
				
			while ($data = dbarray($resultufc)) {
				
				echo "<tr><td class='side-small'>\n";
				echo "<a href='".BASEDIR."profile.php?lookup=".$data['user_id']."' title='".$data['user_name']."'>\n";
				echo "<span>".THEME_BULLET." ".trimlink($data['user_name'], 15)."</a></span>\n";
				echo "</td></tr>\n";
				
			}

		} else {
				echo "<div align='center'>\n";
				echo $locale['userfigure_004'];	
				echo "<p>";
				echo "</div>";				
		}	`

![ashampoo_snap_2016 08 21_16h56m14s_059_](https://cloud.githubusercontent.com/assets/19621858/17837941/39bd51d4-67c0-11e6-9671-fd155c5b1c88.jpg)

**Comment by DavidGuetl** [comment]
Man suche:
```
echo "<tr><td class='side-small'>\n";
            echo "<a href='".BASEDIR."profile.php?lookup=".$data['user_id']."' title='".$data['user_name']."'>\n";
            echo "<span>".THEME_BULLET." ".trimlink($data['user_name'], 15)."</a></span>\n";
            echo "</td></tr>\n";
```

Ersetzte dieses (ungtestet, jeder Benutzer eigene Zeile)
```
echo "<div class='side-small text-center'>
	echo "<a href='".BASEDIR."profile.php?lookup=".$data['user_id']."' title='".$data['user_name']."'>\n";
            echo "<span>".THEME_BULLET." ".trimlink($data['user_name'], 15)."</span>\n";
	echo "</a>\n";
echo "</div>\n";
```

Sollten die Namen nebeneinander dargestellt werden, so setzte die DIV-Befehle auserhalb der Schleife.

**Comment by Catzenjaeger** [comment]
supi funzt :) :+1:
