### ISSUE TITLE
ToDo: statistic

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#24]
- figure with most user count
- the most expensive figure
- figure with .... 

looking for more idea.
I will add this on a statistic site

**Comment by Catzenjaeger** [comment]
last hours i have crate a simple stats page but for some DB results i haven't fount a solution.
atm it looks so:  http://aliencollectors.com/test/infusions/figurelib/panels/figure_stats_panel.php

**Comment by Catzenjaeger** [comment]
stand 22.08.2016 / 11:00 Uhr
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/17849732/7dd7922c-685a-11e6-9bf3-5f6923729a45.JPG)

**Comment by DavidGuetl** [comment]
Sieht doch eh gut aus ;-)

**Comment by Catzenjaeger** [comment]
ich denke da muss aber noch mal drübergecodet werden :)

ich suche noch paar abfragen weiss aber nicht wie ich baseln soll .. aber das ist nicht soooo wichtig im moemtn das kann warten. ist ja schonmal ein grundstock

**Comment by Catzenjaeger** [comment]
hmnn Ladezeiten sind manchmal lang könnte an den abfragen liegen. Frage: wenn man mehrere Abfragen hat ... muss ich dann data immer ändern? also in der ersten data und in der zweiten data2? damit nichts durcheinander kommt?

**Comment by DavidGuetl** [comment]
Nur wenn die Abfrage in der Abfrage ist - Ansonsten nicht.

**Comment by Catzenjaeger** [comment]
ok dann leigts an was anders :) ich beobachte das mal habe gerade gesehen das ein Statement fehlt .. das ist schnell gefixt :)

**Comment by Catzenjaeger** [comment]
problem ist dort: https://github.com/Catzenjaeger/FigureLib_4/issues/36
