### ISSUE TITLE
Verbesserungvorschlag: Jahr Eingabe

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#29]
Habs mal irgendwo gesehen aber weiss nicht wo.

man kann auch das Jahr in etwa so generieren lassen, ohne das man Vorgaben benötigt so wie ich Moment das habe. 

in etwa so: 
		echo form_select_tree("figure_pubdate", $locale['figure_419'], $submitdata['figure_pubdate'], 
			array(
				"inline" => TRUE,
				"required" => TRUE,
				"width" => "400px",
				"placeholder" => $locale['figurelib-placeholder-111'],
				"error_text" => $locale['figurelib-error-109'],
				"minselect" => 1978,
				"maxselect" => 2030,
				"query" => (multilang_table("FI") ? "WHERE figure_year_language='".LANGUAGE."'" : ""),
				"allowclear" => TRUE
			),
		

das funzt aber nicht. Momentan kommen die Jahreszahlen aus der DB Tabelle years wo ich jedes Jahr als Spalte angelegt habe.

Das ganze gibt es ja modern auch als query also nen calender der aufgeht wenn man drauf klickt abe eigentlich gibt es bei Figuren kein Tag ... höchstens Monat.

Weiß nicht ob man dies verbessern könnte und damit auch userfreundlicher

**Comment by DavidGuetl** [comment]
Schließbar, siehe Testseite.

**Comment by Catzenjaeger** [comment]
geil kann man noch die monate oder das quartal dazumachen? Tage gibt eigentlich nicht

**Comment by DavidGuetl** [comment]
# Done

**Comment by Catzenjaeger** [comment]
das ist fett :) geilllll freu mich wie ein kleines kind gerade LOL
