### ISSUE TITLE
Figure deleting

### ISSUE THREAD

**Issue by DavidGuetl** [Catzenjaeger/FigureLib_4#3]
We should also delete the Comments and Ratings of a Figure, if we delete it.

**Comment by Catzenjaeger** [comment]
normally i have implanted it

`// Defuse cleaning	
$inf_droptable[] = DB_FIGURE_CATS;
$inf_droptable[] = DB_FIGURE_ITEMS;
	// wird nicht benötigt aber erstmal lassen
	//$inf_droptable[] = DB_FIGURE_SETTINGS;
$inf_droptable[] = DB_FIGURE_MANUFACTURERS;
$inf_droptable[] = DB_FIGURE_BRANDS;
$inf_droptable[] = DB_FIGURE_MATERIALS;
$inf_droptable[] = DB_FIGURE_SCALES;
$inf_droptable[] = DB_FIGURE_POAS;
$inf_droptable[] = DB_FIGURE_PACKAGINGS;
$inf_droptable[] = DB_FIGURE_LIMITATIONS;
$inf_droptable[] = DB_FIGURE_MEASUREMENTS;
$inf_droptable[] = DB_FIGURE_USERFIGURES;
$inf_droptable[] = DB_FIGURE_IMAGES;
$inf_droptable[] = DB_FIGURE_YEARS;
$inf_deldbrow[] = DB_COMMENTS." WHERE comment_type='FI'";
$inf_deldbrow[] = DB_RATINGS." WHERE rating_type='FI'";
$inf_deldbrow[] = DB_ADMIN." WHERE admin_rights='FI'";
$inf_deldbrow[] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/figures.php'";
$inf_deldbrow[] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/submit.php'";
$inf_deldbrow[] = DB_SITE_LINKS." WHERE link_url='infusions/figurelib/mycollection.php'";
$inf_deldbrow[] = DB_LANGUAGE_TABLES." WHERE mlt_rights='FI'";
$inf_deldbrow[] = DB_PANELS." WHERE panel_filename='latest_figures_center_panel'";
$inf_deldbrow[] = DB_SETTINGS_INF." WHERE settings_inf='figurelib'";
// so lange betaphase erstmal auskommentieren weil sond die ganzen submittings weg sind und alle mühesam per hand neu eingereicht werden müssen
//$inf_deldbrow[] = DB_SUBMISSIONS." WHERE submit_type='f'";`

**Comment by DavidGuetl** [comment]
Yes if you delete the complete Addon.

I meant, if we delete only a Figure in Adminarea.

**Comment by Catzenjaeger** [comment]
upps you are right - important.
and what is when i user delete his account? --> NoName

**Comment by DavidGuetl** [comment]
Yes, should be than display "No Name" or "No Account" or sth like that.

**Comment by Catzenjaeger** [comment]
yet something fitting to the theme: I can not do because I do not understand it
https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37781&pid=199580#post_199580

**Comment by DavidGuetl** [comment]
Ok is it enought if we "anonymize" the account?

All Contents will be left in Community, only Profile + Account Name will be delete.

**Comment by Catzenjaeger** [comment]
in Germany a user must be have the opportunity to delete his own account self and delete all data
that must be respected .. well im host in Germany!

**Comment by DavidGuetl** [comment]
So also all Figures, Comments, etc?

**Comment by Catzenjaeger** [comment]
no not figures ... the submitter confirmed in agb that's figures go to aliencollectors ... images too
but members personal data must be deleted (comments = anonymized, ratings = ??? can be delete or?)

**Comment by Catzenjaeger** [comment]
i think this must be at first: https://www.php-fusion.co.uk/forum/viewthread.php?thread_id=37781&pid=199580#post_199580

**Comment by DavidGuetl** [comment]
# close betreffend Admin

Für Account löschen bitte eigene Issue.
