### ISSUE TITLE
Logikfrage: Bildgröße

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#30]
Da ich gerade die Settings umbaue.

momentan wird angegeben wie groß der maximalupload sein darf. Dabei wird aber nicht differenziert ob ein Bild oder 10. Heißt, theoretisch könnte jemand ein Bild mit 5 MB hochladen oder 10 Bilder  mit 5 MB

sollte man das trennen?

Also mittels eine IF abfrage -- nur keinen Ahnung ob das dynamisch überhaupt geht. 
Beispiel 

if Bildanzahl= größer/gleich 1 dann settings figure_photo_max_b = xxxxx
else .......

**Comment by DavidGuetl** [comment]
Naja die grösse die du angibst ist pro Datei erlaubt, wär ja logisch oder

**Comment by Catzenjaeger** [comment]
heisst so wie jetzt  könnte man 10 x 5 MB hochladen? das wäre ja doof das sprengt ja bei 1000 Figuren alles :)

**Comment by DavidGuetl** [comment]
Könnte man aber wer tut dass?

Auserdem naja du hast sicher genug Speicher oder?

**Comment by Catzenjaeger** [comment]
LOL david du müsstest das doch das wissen -- wer tut so etwas?? ROFL -- es gibt immer deppen 
übrigens formular seetings steht soweit

**Comment by DavidGuetl** [comment]
Naja das Problem ist, was wenn du jetzt 10 Bilder mit maximal 10mb hast ..

1bild 2 mb
2bilder jeweils 500kb

Das geht also nicht :P

**Comment by DavidGuetl** [comment]
Einfach 1 mb einstellen dann kann zb jedes bild 1 mb haben

**Comment by Catzenjaeger** [comment]
ok mache ich - closed
