### ISSUE TITLE
FRAGE:  zu settings wo werden bilder den gespeichert

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#31]
Bau das gerade ein ... blöde frage wo werden eigentlich die Bilder und thumbs dann gespeichert? 
also für cat und Manufakturer und thumb 2
das muss doch sicher auch eingerichtet werden

**Comment by DavidGuetl** [comment]
Dachte an weitere Ordner im Ordner images des Addons

**Comment by Catzenjaeger** [comment]
ok geht klar. ok bin für ne stunde  offline mache dann weiter!

**Comment by Catzenjaeger** [comment]
jetzt die frage ob man das alles noch einmal reorganisiert. 
wir haben den Ordner "Figures" wo im Unterordner Images die Figuren Bilder einlaufen
