### ISSUE TITLE
INFO: Ordnerstruktur neu

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#32]
Hallo David hier kurz die Infos das ich die Ordnerstruktur wie folgt geändert/erweitert habe

- figurelib/figures --> Ordner für Figuren Bilder
- figurelib/figures/images --> Figuren Bilder 
- figurelib/figures/images/thumbs --> Figuren Thumbs

- figurelib/categories --> Ordner für Kategorien Bilder
- figurelib/categories/images --> Kategorie Bilder
- figurelib/categories/images/thumbs --> Kategorie Thumbs

- figurelib/manufacturer --> Ordner für Manufacturer Bilder
- figurelib/manufacturer/images --> Manufacturer Bilder
- figurelib/manufacturer/images/thumbs --> manufacturer Thumbs

warum der Thumb Ordner immer unterhalb liegen muss weiß ich nicht aber das ging wohl nicht anders. Ich habe alle Ordner bereits hier in Github erstellt.

Die Datei indusions.db muss angepast werden wenn ich  mich nicht irre 
das mache ich noch

**Comment by DavidGuetl** [comment]
Laden wir thumb2 auch in den thumb ordner?

Und wieso nicht ein Ordner "images", darin jeweils "categories", "figures", "manufacturers" und darin wieder die thumbs ordner.

Schussendlich ist es natürlich am ende deine entscheidung :-)

**Comment by Catzenjaeger** [comment]
Und wieso nicht ein Ordner "images", darin jeweils "categories", "figures", "manufacturers" und darin wieder die thumbs ordner. --> das wäre auch meine idee gewesen und auch vorschlag. Aber ich hatte das mal probiert den Ordner thumbs eine ebene höher zu schieben aber das ging nicht. Warum auch immer. 
Wir können das gerne umstrukturieren -- wäre auch einleuchtend -- alles unter images zu haben -- weil dort würde ich auch suchen :)

soll ich mal umbauen? Aber dann müssen die submit.php und die ganzen admin files angepasst werden
induion.db auch

**Comment by Catzenjaeger** [comment]
schau mal so???
![ashampoo_snap_2016 08 22_19h28m42s_001_](https://cloud.githubusercontent.com/assets/19621858/17864806/e97b440c-689f-11e6-8cab-b7193c609d91.jpg)

**Comment by Catzenjaeger** [comment]
das hier muss angepasst werden .. ich mach das mal  (ist in infusion.db.php)

	// FOLDERS
if (!defined("FIGURES")) {
	define("FIGURES", INFUSIONS.$inf_folder."/figures/");
}
if (!defined("IMAGES_FIGURES")) {
	define("IMAGES_FIGURES", INFUSIONS.$inf_folder."/figures/images/");
}
if (!defined("THUMBS_FIGURES")) {
	define("THUMBS_FIGURES", INFUSIONS.$inf_folder."/figures/images/thumbs/");
}

**Comment by DavidGuetl** [comment]
Ja so wäre die Struktur super :P

**Comment by Catzenjaeger** [comment]
wäre das hier richtig?

	// FOLDERS for Figures
if (!defined("FIGURES")) {
	define("FIGURES", INFUSIONS.$inf_folder."/images/figures/");
}
if (!defined("IMAGES_FIGURES")) {
	define("IMAGES_FIGURES", INFUSIONS.$inf_folder."/images/figures/images/");
}
if (!defined("THUMBS_FIGURES")) {
	define("THUMBS_FIGURES", INFUSIONS.$inf_folder."/images/figures/thumbs/");
}
if (!defined("THUMBS2_FIGURES")) {
	define("THUMBS2_FIGURES", INFUSIONS.$inf_folder."/images/figures/thumbs2/");
}

	// FOLDERS for Categories
if (!defined("CATEGORIES")) {
	define("CATEGORIES", INFUSIONS.$inf_folder."/images/categories/");
}
if (!defined("IMAGES_CATEGORIES")) {
	define("IMAGES_CATEGORIES", INFUSIONS.$inf_folder."/images/categories/images/");
}
if (!defined("THUMBS_CATEGORIES")) {
	define("THUMBS_CATEGORIES", INFUSIONS.$inf_folder."/images/categories/thumbs/");
}

	// FOLDERS for Manufacturers
if (!defined("MANUFACTURERS")) {
	define("MANUFACTURERS", INFUSIONS.$inf_folder."/images/manufacturers/");
}
if (!defined("IMAGES_MANUFACTURERS")) {
	define("IMAGES_MANUFACTURERS", INFUSIONS.$inf_folder."/images/manufacturers/images/");
}
if (!defined("THUMBS_MANUFACTURERS")) {
	define("THUMBS_MANUFACTURERS", INFUSIONS.$inf_folder."/images/manufacturers/thumbs/");
}

**Comment by Catzenjaeger** [comment]
file infusions.db.php --> updatet inGithub --https://github.com/Catzenjaeger/FigureLib_4/blob/master/infusions/figurelib/infusion_db.php

**Comment by DavidGuetl** [comment]
Ja sieht ganz gut aus :-)

**Comment by Catzenjaeger** [comment]
aber jetzt müssen die submit und die admin_figurelib auch angepasst werden! die ganzen submit sachen und auch dort wo es ausgelesen wird

**Comment by DavidGuetl** [comment]
Dass mache ich in der Nacht, schreib dazu einige Funktionen

**Comment by Catzenjaeger** [comment]
was soll ich jetzt noch machen?

**Comment by Catzenjaeger** [comment]
also lasse ich alles so wie es ist?
sooll ich nochmal neu installieren - wegen den änderungen in den files?

**Comment by DavidGuetl** [comment]
Würde sagen erst morgen nach den Änderungen:-)

**Comment by Catzenjaeger** [comment]
habe es gerade neu installiert weil ich auch die links in der Navigation 
angepasst habe -- allerdings muss da mal jemand über den code in 
infusions.php schauen

// Create a link for all installed languages
if (!empty($enabled_languages)) {
     foreach($enabled_languages as $language) {
         include LOCALE.$language."/setup.php";
         // add new language records
         $mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, 
link_url, link_visibility, link_position, link_window, link_order,     
     link_language) VALUES ('".$locale['INF_TITLE']."', 
'infusions/figurelib/figures.php', '0', '2', '0', '2', '".$language."')";

         $mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, 
link_url, link_visibility, link_position, link_window, link_order, 
link_language) VALUES ('".$locale['mycollection']."', 
'infusions/figurelib/mycollection.php', ".USER_LEVEL_MEMBER.", '2', '0', 
'3', '".$language."')";

         $mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, 
link_url, link_visibility, link_position, link_window, link_order, 
link_language) VALUES ('".$locale['figure_521']."', 
'infusions/figurelib/submit.php?stype=f', ".USER_LEVEL_MEMBER.", '2', 
'0', '4', '".$language."')";

         //$locale['figure_533'] = "Figure Stats";
         $mlt_insertdbrow[$language][] = DB_SITE_LINKS." (link_name, 
link_url, link_visibility, link_position, link_window, link_order, 
link_language) VALUES ('".$locale['figure_533']."', 
'infusions/figurelib/panels/figure_stats_panel.php', 
".USER_LEVEL_MEMBER.", '2', '0', '4', '".$language."')";


         // drop deprecated language records
         $mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE 
link_url='infusions/figurelib/figures.php' AND 
link_language='".$language."'";
         $mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE 
link_url='infusions/figurelib/mycollection.php' AND 
link_language='".$language."'";
         $mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE 
link_url='infusions/figurelib/submit.php?stype=f' AND 
link_language='".$language."'";
         $mlt_deldbrow[$language][] = DB_SITE_LINKS." WHERE 
link_url='infusions/figurelib/panels/figure_stats_panel.php' AND 
link_language='".$language."'";
         $mlt_deldbrow[$language][] = DB_FIGURE_CATS." WHERE 
figure_cat_language='".$language."'";
     }
} else {
         $inf_insertdbrow[] = DB_SITE_LINKS." (link_name, link_url, 
link_visibility, link_position, link_window, link_order, link_language) 
VALUES('".$locale['setup_3307']."', 'infusions/figurelib/figures.php', 
'0', '2', '0', '2', '".LANGUAGE."')";
}
/*
################################################



Am 22.08.2016 um 20:17 schrieb David:

**Comment by Catzenjaeger** [comment]
hier das ganze file habe es hier geupdated: https://github.com/Catzenjaeger/FigureLib_4/blob/master/infusions/figurelib/infusion.php

das mit den Links und den languages stimmt bestimmt nicht 100% -- chan sollte da mal reinschauen er hats ja erfunden :)
ich blicke da nicht so ganz durch

**Comment by DavidGuetl** [comment]
Betreffend Ordner hat sich einiges geändert. Gib dir das nachher dann durch.

**Comment by Catzenjaeger** [comment]
ok super

**Comment by DavidGuetl** [comment]
```
// FOLDERS for Figures
if (!defined("FIGURES")) {
	define("FIGURES", INFUSIONS.$inf_folder."/images/figures/"); 
}
if (!defined("THUMBS_FIGURES")) {
	define("THUMBS_FIGURES", INFUSIONS.$inf_folder."/images/figures/thumbs/");
}

// FOLDERS for Categories
if (!defined("CATEGORIES")) {
	define("CATEGORIES", INFUSIONS.$inf_folder."/images/categories/");
}
if (!defined("THUMBS_CATEGORIES")) {
	define("THUMBS_CATEGORIES", INFUSIONS.$inf_folder."/images/categories/thumbs/");
}

// FOLDERS for Manufacturers
if (!defined("MANUFACTURERS")) {
	define("MANUFACTURERS", INFUSIONS.$inf_folder."/images/manufacturers/");
}
if (!defined("THUMBS_MANUFACTURERS")) {
	define("THUMBS_MANUFACTURERS", INFUSIONS.$inf_folder."/images/manufacturers/thumbs/");
}
```

Ordnerstruktur (ausgehend von Verzeichnis figurelib)

> - images/
> --- categories/
> ----- thumbs/
> --- figures
> ----- thumbs/
> --- manufacturers
> ----- thumbs/

**Comment by Catzenjaeger** [comment]
stimmt das wirklich .. weil es fehlt doch thumb2 oder kommt das  mit in den normalen thumb ordner

**Comment by DavidGuetl** [comment]
Normalen .. ist in der v9 so gehandhabt

**Comment by Catzenjaeger** [comment]
ich hoffe ich habe die Struktur
![ashampoo_snap_2016 08 24_18h25m41s_001_](https://cloud.githubusercontent.com/assets/19621858/17938881/286d5126-6a28-11e6-88d3-d7e50e9dc7a1.jpg)
 jetzt richtig :)

**Comment by DavidGuetl** [comment]
Jops und Jops

**Comment by Catzenjaeger** [comment]
done
