### ISSUE TITLE
Suche Abfrage für "welche Figur am meisten in Userbesitz"

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#33]
Möchte gerne herausfinden welche Figur am meisten in Userbesitz ist:

mein Code ist falsch ...  

will das hier einbauen: http://aliencollectors.com/test/infusions/figurelib/panels/figure_stats_panel.php

`	$resultmostusercount = dbquery("
					SELECT 
						tb.figure_id, tb.figure_submitter, tb.figure_retailprice, tb.figure_usedprice, tb.figure_freigabe, tb.figure_pubdate, tb.figure_scale, tb.figure_title, tb.figure_manufacturer, tb.figure_brand, tb.figure_datestamp, tb.figure_cat, 
						tbc.figure_cat_id, tbc.figure_cat_name, 
						tbu.user_id, tbu.user_name, tbu.user_status, tbu.user_avatar, 
						tbm.figure_manufacturer_name, 
						tbb.figure_brand_name, 
						tby.figure_year_id, tby.figure_year, 
						tbs.figure_scale_id, tbs.figure_scale_name, 							
						fuf.figure_userfigures_figure_id, fuf.figure_userfigures_user_id 
					FROM ".DB_FIGURE_ITEMS." AS tb
					LEFT JOIN ".DB_USERS." AS tbu ON tb.figure_submitter=tbu.user_id
					LEFT JOIN ".DB_FIGURE_USERFIGURES." AS fuf ON fuf.figure_userfigures_figure_id=tb.figure_id
					LEFT JOIN ".DB_FIGURE_CATS." AS tbc ON tb.figure_cat=tbc.figure_cat_id
					LEFT JOIN ".DB_FIGURE_MANUFACTURERS." AS tbm ON tbm.figure_manufacturer_id = tb.figure_manufacturer
					LEFT JOIN ".DB_FIGURE_BRANDS." AS tbb ON tbb.figure_brand_id = tb.figure_brand
					LEFT JOIN ".DB_FIGURE_SCALES." AS tbs ON tbs.figure_scale_id = tb.figure_scale
					LEFT JOIN ".DB_FIGURE_YEARS." AS tby ON tby.figure_year_id = tb.figure_pubdate
					WHERE ".(multilang_table("FI") ? "tb.figure_language='".LANGUAGE."' AND" : "")." tb.figure_freigabe='1' 
					ORDER BY fuf.figure_userfigures_figure_id DESC LIMIT 0,1 
				");`

**Comment by DavidGuetl** [comment]
```
$resultmostusercount = dbquery("
					SELECT 
						tb.figure_id, tb.figure_submitter, tb.figure_retailprice, tb.figure_usedprice, tb.figure_freigabe, tb.figure_pubdate, tb.figure_scale, tb.figure_title, tb.figure_manufacturer, tb.figure_brand, tb.figure_datestamp, tb.figure_cat, 
						tbc.figure_cat_id, tbc.figure_cat_name, 
						tbu.user_id, tbu.user_name, tbu.user_status, tbu.user_avatar, 
						tbm.figure_manufacturer_name, 
						tbb.figure_brand_name, 
						tbs.figure_scale_id, tbs.figure_scale_name, 							
						fuf.figure_userfigures_figure_id, fuf.figure_userfigures_user_id,
						count(fuf.figure_userfigures_user_id) AS users_counter
					FROM ".DB_FIGURE_ITEMS." AS tb
					LEFT JOIN ".DB_USERS." AS tbu ON tb.figure_submitter=tbu.user_id
					LEFT JOIN ".DB_FIGURE_USERFIGURES." AS fuf ON fuf.figure_userfigures_figure_id=tb.figure_id
					LEFT JOIN ".DB_FIGURE_CATS." AS tbc ON tb.figure_cat=tbc.figure_cat_id
					LEFT JOIN ".DB_FIGURE_MANUFACTURERS." AS tbm ON tbm.figure_manufacturer_id = tb.figure_manufacturer
					LEFT JOIN ".DB_FIGURE_BRANDS." AS tbb ON tbb.figure_brand_id = tb.figure_brand
					LEFT JOIN ".DB_FIGURE_SCALES." AS tbs ON tbs.figure_scale_id = tb.figure_scale
					WHERE ".(multilang_table("FI") ? "tb.figure_language='".LANGUAGE."' AND" : "")." tb.figure_freigabe='1' 
					GROUP BY fuf.figure_userfigures_figure_id
					ORDER BY users_counter DESC LIMIT 0,5");
```

**Comment by Catzenjaeger** [comment]
ne leider nicht

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18001054/512e9962-6b81-11e6-8740-331cdf7a066a.JPG)

**Comment by DavidGuetl** [comment]
evtl hat die Figure ein anderer in seiner Sammlung?

**Comment by Catzenjaeger** [comment]
ne ich habe nur die eine drin :) die DB userfigures ist leer

**Comment by Catzenjaeger** [comment]
übrigens der counter oben zählt alle Figuren aller user -- :) wenn der null ist darf unten eigentlich nichts stehen

**Comment by DavidGuetl** [comment]
Uff .. ich seh mir dass an wenn ich mal bisschen mehr Zeit habe :P

**Comment by Catzenjaeger** [comment]
ok das andere ist wichtiger hast recht :)
