### ISSUE TITLE
Aufgelaufene Fehler/Notices

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#34]
für dich zur info in den settings des Adminbereich. Ich wollte jetzt nicht in den files rumfummeln deshalb lass ich es. erst wenn go gibtst

admin/admin_figurelib_settings.php
/test/infusions/figurelib/admin.php?aid=09d859ebad6a4f91&section=figurelib_settings
Undefined index: figure_photo_man_max_h
Line: 459

Run-time notices 	
admin/admin_figurelib_settings.php
/test/infusions/figurelib/admin.php?aid=09d859ebad6a4f91&section=figurelib_settings
Undefined index: figure_photo_man_max_w
Line: 455

Run-time notices 	
admin/admin_figurelib_settings.php
/test/infusions/figurelib/admin.php?aid=09d859ebad6a4f91&section=figurelib_settings
Undefined index: figure_photo_cat_max_h
Line: 387

Run-time notices 	
admin/admin_figurelib_settings.php
/test/infusions/figurelib/admin.php?aid=09d859ebad6a4f91&section=figurelib_settings
Undefined index: figure_thumb2_ratio
Line: 62

Run-time notices 	
admin/admin_figurelib_settings.php
/test/infusions/figurelib/admin.php?aid=09d859ebad6a4f91&section=figurelib_settings
Undefined index: figure_photo_cat_max_w

**Comment by DavidGuetl** [comment]
Kannst schließen, habe ich behoben.
