### ISSUE TITLE
Form Validierung

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#35]
habe was interessantes über Validieren gefunden was sicher im submit geil wäre.

http://v4-alpha.getbootstrap.com/components/forms/#validation

**Comment by DavidGuetl** [comment]
Gabs bei der vorgänger Version von Bootstrap ebenfalls schon - ist aber bei PHP-Fusion ohne Core Eingriff schwer machbar.

**Comment by Catzenjaeger** [comment]
ah ok ich dachte das kann man easy jeden feld zufügen .. wäre ja cool

**Comment by Catzenjaeger** [comment]
NA DANN KANN DAS ZU WIEDER
