### ISSUE TITLE
IDEA: add some more user collection fields

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#37]
meine Idee: zur Tabelle Userfigures wo die daten eine jeder mycollection zu finden ist dort noch einzutragen :+1: 
- Kaufpreis
- Verkaufpreis
- zu verkaufen
- Verkaufspreis

etc

so könnte man zum Beispiel machen, das ein Member immer zu seiner Figur dazu schreiben kann für wieviel er die gekauft hat. Das wäre ne klasse Sache und am ende herauszubekommen wieviel man in seine Sammlung gesteckt hat.

**Comment by DavidGuetl** [comment]
Merge mit #41 ?
