### ISSUE TITLE
Fehlerliste

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#38]
**FEHLER MEMBEBEREICH**

- [x]  Beim editieren einer Figur sollte die Videourl wieder als Vorschau sichtbar sein damit der Admin sieht welches Video das ist.
- [x]  Fehler in Categories (Adminbereich)-- wenn ich einen neue anlege wird die nachfolgende Liste komplett verschoben -- das war aber einen Subkategorie die ich angelegt habe!
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/17923382/376a44a2-69e4-11e6-8f00-ab0458b186ba.JPG)
- [ ] AMAZON LINKS (amdinbereich und User) nicht als Bild sichtbar

--------------------------------

**FEHLER USERBEREICH**

- [ ] submit -->  Fehler - hatte gerade probiert eine Figur einzusenden mit vielen und großen bildern .. die Figur kam trotz Erfolgsmeldung nicht an!
- [ ] /figures.php --> no cat images
- [ ]  /figurelib/figures.php?figure_cat_id=2 no manufacturer images
- [ ]  /figures.php?figure_id=10 --> Figuren nicht sichtbar

**VERBESSERUNGEN  USERBEREICH**
- [ ] /submit.php?stype=f   --> Limitation Sichtbarkeit des Feldes darunter sollte bei wert UNKNOWN auch deaktiviert sein
- [ ] submit --> Max. file-size 476.84MB / Max. image upload count: 10 / Allowed file-types GIF, JPEG or PNG. --> sollte eventuell zu besseren Kenntlichkeit untereinander gelistet werden ... oder? 
- [ ] submit --> I have read and agree to the terms and conditions. * --> sieht gequetscht aus -- -umformatieren?
- [ ] submit --> die komische Weltkugel kann doch eigentlich auch weg
- [ ] submit -- kein Fehler! aber könnte man bei den Feldern wo man zahlen eintippen muss auch Slider machen also diese Schieberegler. Ich hatte das schon mal versucht ging auch aber hatte die Seite layouttechnisch verhunzt. So würde man Fehleingaben entgegenwirken.  Damals am anfang wo ich das eingebaut hatte wurden die werte wurden nicht dargestellt kann sein das PHF) das nicht unterstützt http://seiyria.com/bootstrap-slider/ 
- [ ] submit (Userbereich)--> Video URL  -- könnte dort auch einen Vorschau machen das sowie der user dort was eingibt untendrunter das video zu sehen wäre damit er weiss es ist richtig?
- [ ] Editbereich einer Figur (Adminbereich) --> den Bereich ganz oben VISIBILITY / PUBLISHING 2 spaltig machen . Die 3 checkboxen n ach rechts um Platz zu sparen

**IDEE USERBEREICH**
- [ ] submit & Allgemein IDEE --> ein bild als Titelbild auswählen. Für den user sicher nicht so wichtig aber als adminfunktion vielleicht geil wenn jemand 10 Bilder einschickt und das nicht gerade das Bild der Bodenplatte das Titelbild wäre. der admin müsste die Bilder sortieren können
- [ ] IDEE Suchbutton damit man schneller eine Figur findet. Ich denke wenn dann bei Sideshow oder NAECA 100 Figuren sind muss man ewig klicke um einen bestimmte zu finden. Oder man macht einen Umschaltseite wo der user auswählt Listenansicht, Kompaktansicht, ausführliche liste

**Comment by DavidGuetl** [comment]
Kannst du mir evtl noch in Klammer schreiben, was Admin und was User Bereich betrifft?

Ist ja doch eine recht ordentliche Liste :o

**Comment by Catzenjaeger** [comment]
ja aber viele Sachen sind Kleinigkeiten oder sachen die nicht unbedingt müssen
Du musst auch dran denken das alles was submit betriftt eigentlich auch in der admin area unter admin_figurelib betrifft. ist ja quasi auch ein submit

**Comment by DavidGuetl** [comment]
Jap, wie gesagt, die ganzen öffentlichen Dateien sind noch nicht up-to-date, deshalb fällts mir leichter wenn du das ggf. markieren könntest in deiner Liste ;-)

**Comment by Catzenjaeger** [comment]
so ok?

**Comment by DavidGuetl** [comment]
Bombe :-)

**Comment by DavidGuetl** [comment]
Betreffend Amazon Links -> Du hast mir keine Flaggen mit hochgeladen :)

**Comment by Catzenjaeger** [comment]
mach ich gleich :)

**Comment by DavidGuetl** [comment]
Geh mal auf meine Testseite, Figur Einsenden, meitest du so die Spalte oben, die AGBs, das Video, sowie Limitation?

**Comment by Catzenjaeger** [comment]
Geh mal auf meine Testseite, Figur Einsenden, meitest du so die Spalte oben, die AGBs, das Video, sowie Limitation? --> nichts zu sehen????
 
ps.: Streich es gleich aus der Liste wenn es passt.

Kategorien/Manufacturers/Brands sind ebenfalls gefixt und mit Bild versehen. --> hier auch nicht -- daten hochgeladen?

**Comment by DavidGuetl** [comment]
Betrifft nur Adminbereich :-) die aktualisierungen

**Comment by Catzenjaeger** [comment]
lol :)

**Comment by Catzenjaeger** [comment]
klasse :+1:  :+1: :+1:

**Comment by DavidGuetl** [comment]
Könnte man .. aber ist meiner Ansicht nach für die kurze Zeit zu aufwendig.

**Comment by Catzenjaeger** [comment]
Beim Datum muss irrgendwie wenn möglich auch unknown rein -- geht das? weil was ist wenn der user es nicht weis?

**Comment by DavidGuetl** [comment]
Naja dann das fehlt evtl. einfach leer lassen - mit Datepicker geht dass nicht.

**Comment by DavidGuetl** [comment]
http://phpfusion-development.at/figurelib.zip

Darin wären alle Files von der Administration inklusive dem neuen functions-File und der neuen Ordnerstruktur für Image (nur die Erweiterungen)

Bitte alle Änderungen was du durchführen möchtest auf Basis dieser Files machen.

Werde morgen den Userbereich abarbeiten, also bitte aufjedenfall schauen, dass alle Dateien aktuell sind wenn du für Heute schluss machst. Beachte, dass eine Anzeige der Figuren auserhalb des Admins derzeit nicht möglich ist.

**Comment by DavidGuetl** [comment]
Desweiteren folgende Spalten anlegen:
FIGURE_CATS
- figure_cat_image VARCHAR(255) NOT NULL DEFAULT ''
- figure_cat_thumb VARCHAR(255) NOT NULL DEFAULT ''

FIGURE_MANUFACTURERS
- figure_manufacturer_image VARCHAR(255) NOT NULL DEFAULT '',
- figure_manufacturer_thumb VARCHAR(255) NOT NULL DEFAULT '',

FIGURE_IMAGES
- figure_images_image_thumb2 VARCHAR(255) NOT NULL DEFAULT ''

**Comment by Catzenjaeger** [comment]
können wir das hier noch ändern?

		figure_images_image_id MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT, 
		figure_images_figure_id VARCHAR(100) NOT NULL DEFAULT '',
		figure_images_image VARCHAR(100) NOT NULL DEFAULT '',
		figure_images_thumb VARCHAR(100) NOT NULL DEFAULT '',
		figure_images_image_thumb2 VARCHAR(255) NOT NULL DEFAULT ''
		figure_images_sorting VARCHAR(50) NOT NULL DEFAULT '',
		figure_images_language VARCHAR(50) NOT NULL DEFAULT '".

also das figure_images_image_thumb2
zu figure_images_thumb2

damit es passend zu den anderen ist :)

**Comment by DavidGuetl** [comment]
Habe ja eh figure_images_thumb2 geschrieben o.O

Naja bedeutet eben bis maximal 100 bzw 255 zeichen. Mit 255 is man zu 100% sicher

**Comment by Catzenjaeger** [comment]
soll ich die anderen auf 255 ändern?

**Comment by DavidGuetl** [comment]
Könntest du um auf Nummer sicher zu geheb

**Comment by Catzenjaeger** [comment]
ok mache ich .. ich zeihe mir gerade das neu php f 9 damit ich die aktuellsten daten habe .. FrederickChan schraubt die ganze Zeit rum :)
ich installiere dann neu besser mal

**Comment by Catzenjaeger** [comment]
also ich habe alles hochgeladen ... aber zig Fehler .. log dich mal ein
die Zugangsdaten sind die gleichen "Test " wie auf deiner Testseite
in deinen doenloadpaket waren die Ordner durcheinander oder hat sich die Struktur geändert? functions ist dazugekommen habe ich gesehen

**Comment by DavidGuetl** [comment]
Hab kein Admin Zugriff - Was sind zig Fehler? Chmods gesetzt?

**Comment by Catzenjaeger** [comment]
admin zugriff ok sorry hatte ich vergessen ..
ich ändere noch die paar core Datein ab dann sollte funzen .. ein Fehler ist aber drin schau mal

**Comment by DavidGuetl** [comment]
Kategorie Tabelle wurde nicht angelegt 🙂

**Comment by Catzenjaeger** [comment]
DB tabelle years wird ja eigentlich nicht mehr gebraucht

**Comment by DavidGuetl** [comment]
Nein die kannst du entfernen

**Comment by Catzenjaeger** [comment]
kommas fehlten :) ok ich fixe das und adde auch gleich die 4 neuen settings die ich noch benötig inclusive den vorgabe werten bei installation

**Comment by DavidGuetl** [comment]
Ok

**Comment by Catzenjaeger** [comment]
das ist neu

$inf_insertdbrow[] = DB_SETTINGS_INF." (settings_name, settings_value, settings_inf) VALUES('figure_allow_submit_videos', '1', 'figurelib')";
$inf_insertdbrow[] = DB_SETTINGS_INF." (settings_name, settings_value, settings_inf) VALUES('figure_show_videos', '1', 'figurelib')";

$inf_insertdbrow[] = DB_SETTINGS_INF." (settings_name, settings_value, settings_inf) VALUES('figure_affiliate', '1', 'figurelib')";
$inf_insertdbrow[] = DB_SETTINGS_INF." (settings_name, settings_value, settings_inf) VALUES('figure_amazon', '1', 'figurelib')";
$inf_insertdbrow[] = DB_SETTINGS_INF." (settings_name, settings_value, settings_inf) VALUES('figure_ebay', '1', 'figurelib')";
$inf_insertdbrow[] = DB_SETTINGS_INF." (settings_name, settings_value, settings_inf) VALUES('figure_display', '1', 'figurelib')";
$inf_insertdbrow[] = DB_SETTINGS_INF." (settings_name, settings_value, settings_inf) VALUES('figure_submit', '1', 'figurelib')";
$inf_insertdbrow[] = DB_SETTINGS_INF." (settings_name, settings_value, settings_inf) VALUES('figure_related', '1', 'figurelib')";
$inf_insertdbrow[] = DB_SETTINGS_INF." (settings_name, settings_value, settings_inf) VALUES('figure_social_sharing', '1', 'figurelib')";

**Comment by DavidGuetl** [comment]
Baust du es eh Gleich ein im Admin? 😁

**Comment by Catzenjaeger** [comment]
ja ich baue das dann ein aber nicht sofort

aber ich habe noch scheiss fehler

Driver/PDOMySQL.php
/test/administration/infusions.php?aid=d1a454ccfd259723
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'figure_images_sorting VARCHAR(50) NOT NULL DEFAULT '', figure_images_language ' at line 7
Line: 72
2 seconds ago

**Comment by Catzenjaeger** [comment]
so scheint alles sauer zu sein zumindest nach installation :)

**Comment by Catzenjaeger** [comment]
so die settings sind umgebaut
hier mal ein Bild. Ich lade die datei gleich mal dann kannste mal chckcen ob dort alles ok ist
![ashampoo_snap_2016 08 24_19h48m25s_002_](https://cloud.githubusercontent.com/assets/19621858/17941523/040ffa20-6a34-11e6-8bbe-2704f1586892.jpg)

**Comment by DavidGuetl** [comment]
Gefällt mir sehrgut :-)

**Comment by Catzenjaeger** [comment]
:) die Panels usw gehen nicht mehr da das Jahr nicht mehr vorhanden ist. ich lade jetzt mal alles neu hier ins github damit das aktuell ist

**Comment by DavidGuetl** [comment]
Ja behebe dass morgen dann :-)

**Comment by Catzenjaeger** [comment]
könnstest du nochmal schauen nach den DB Abfragen wo ich probleme habe .. das dürfte nichts großartiges sein

**Comment by DavidGuetl** [comment]
Nachher/Morgen muss die selbst erst testen :P

**Comment by Catzenjaeger** [comment]
das hier sehr unübersichtlich mache ich das mal zu. Die fehler ab jetzt wieder einzeln .. ich denke das ist besser :)
