### ISSUE TITLE
Frage für später Erweiterung Memberbereich

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#41]
Idee: zur Tabelle Userfigures wo die daten eine jeder mycollection zu finden ist dort noch einzutragen :+1:

    Kaufpreis
    Verkaufpreis
    zu verkaufen
    Verkaufspreis

etc

so könnte man zum Beispiel machen, das ein Member immer zu seiner Figur dazu schreiben kann für wieviel er die gekauft hat. Das wäre ne klasse Sache und am ende herauszubekommen wieviel man in seine Sammlung gesteckt hat.

ich möchte die userifguren noch bissel erweitern.
Dazu möchte ich mehrere Felder noch einfügen

--> Member möchte diese Figur verkaufen -> figure_userfigures_for_sale --> da nur ja /nein
--> Verkaufspreis der Figur -> figure_userfigures_sale_price
--> Versandkosten -> figure_userfigures_shipping_costs
--> Figur verkauf -> figure_userfigures_sold --> nur ja/nein
--> Member möchte diese Figur tauschen --> figure_userfigures_for_trade --> auch hier ja/nein
--> Einkaufspreis der figur -> figure_userfigures_purchase_price

dazu habe ich das hier in die userfigures DB Table angedacht

ist das korrekt und auch vom english richtig?
figure_userfigures_purchase_price VARCHAR(100) NOT NULL DEFAULT '',
figure_userfigures_sale_price VARCHAR(100) NOT NULL DEFAULT '',		
figure_userfigures_shipping_costs VARCHAR(100) NOT NULL DEFAULT '',		
figure_userfigures_for_sale TINYINT(1) UNSIGNED NOT NULL DEFAULT '0,  --> muss nur ja /nein
figure_userfigures_for_trade TINYINT(1) UNSIGNED NOT NULL DEFAULT '0', --> muss nur ja /nein
figure_userfigures_sold UNSIGNED NOT NULL DEFAULT '0', --> muss nur ja /nein
figure_userfigures_sorting VARCHAR(50) NOT NULL DEFAULT '',	

in der figure_items kommt nur noch ein spalte rein --> figure_wanted_by_member VARCHAR(400) NOT NULL DEFAULT '',
Dort soll der Member quasi ankreuzen können das er diese Figur sucht. Da diese dann logischerweise noch nicht in seinen besitzt ist , sonst würde er ja nicht suchen ... muss das dorthin damit alle figuren abgedeckt sind. eingetragen werden sollen aber dort alle usernamen die die Figur suchen damit man eine Übersicht und auch Statistik hat

**Comment by DavidGuetl** [comment]
Ansich korrekt, wobei allerdings sorting?

**Comment by Catzenjaeger** [comment]
hmnn  das war überall so drin :) keinen ahnung ob man das braucht zb um siene figuren zu sortieren

2 spalten fehlen noch --> 
gekauft am --> bought at
gekauft wo --> buy where

**Comment by DavidGuetl** [comment]
sorting ergibt nur sinn bei "manufacturer" und "categories" -> aber nicht mal dort wirklich weil angewendet wirds eh nicht ..^^

**Comment by Catzenjaeger** [comment]
also haue ich es raus? 

schau über meinen variablen -- mache so sinn oder schreibt man das anders (wegen englisch) soll ja eindeutig erkennbar sein was man mit der variable meint

**Comment by DavidGuetl** [comment]
Ja.

Ja würde sagen dass passt.

**Comment by Catzenjaeger** [comment]
das wäre komplette Tabelle

$inf_newtable[] = DB_FIGURE_USERFIGURES." (
		figure_userfigures_id MEDIUMINT(8) UNSIGNED NOT NULL AUTO_INCREMENT, 
		figure_userfigures_figure_id VARCHAR(100) NOT NULL DEFAULT '',
		figure_userfigures_user_id VARCHAR(100) NOT NULL DEFAULT '',		
		figure_userfigures_purchase_price VARCHAR(100) NOT NULL DEFAULT '',
		figure_userfigures_bought_at VARCHAR(100) NOT NULL DEFAULT '',
		figure_userfigures_buy_where VARCHAR(100) NOT NULL DEFAULT '',	
		figure_userfigures_sale_price VARCHAR(100) NOT NULL DEFAULT '',		
		figure_userfigures_shipping_costs VARCHAR(100) NOT NULL DEFAULT '',		
		figure_userfigures_for_sale TINYINT(1) UNSIGNED NOT NULL DEFAULT '0', 
		figure_userfigures_for_trade TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
		figure_userfigures_sold TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',	
		figure_userfigures_language VARCHAR(50) NOT NULL DEFAULT '".LANGUAGE."',
PRIMARY KEY (figure_userfigures_id)
	) ENGINE=MyISAM DEFAULT CHARSET=UTF8 COLLATE=utf8_unicode_ci";

**Comment by DavidGuetl** [comment]
Würde mir nichts auffallen.

**Comment by Catzenjaeger** [comment]
danke :+1:

**Comment by Catzenjaeger** [comment]
ist alles eingefügt deshalb mache ich das vorläufig mal zu
