### ISSUE TITLE
ERROR: allow comments allow .. usw.

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#43]
ich mache das mal neu auf weil es doch hier ein Missverständnis gab

diese settings gibt es einmal global für alle Figuren aber auch für die einzelne figure. Ich habe gesehen das du in der neuen admin/admin_figurelib.php alles auf die globale Variante umgeschrieben hast. Das ist dort aber nicht richtig. In diesen Fall wird ja eine Figur editiert, angelegt oder gelöscht. -- also ist das dort auf die Figur bezogen was in der DB_ITEMS gespeichert wird

Also die Settings werden in der infusions_setting DB von PHPF9 gespeichert.
Die Settings der einzelnen Figur jeweils zu jeder einzelnen Figur pro ID in die FIGURE_ITEMS

jetzt bin gerade echt überfordert das wieder hinzubiegen .. das tut mir voll leid aber da müssen wir noch einmal ran. Das ist natürlich sehr unglücklich gewählt auch von den Bezeichnungen .. eventuell sollte man da mal nachbessern.

Ich würde neben der neuen admin/admin/admin_figurelib.php auch noch mal die alte Version hochladen .. oder hast die noch? 
In FIGURE_ITEMS müssen auch noch die spalten allow video , allow affiliate, amazon und ebay rein. Das soll nämlich pro Figur ausschaltbar sein aber auch global für alle auf einmal. 

Mir ist das nur zufällig gerade aufgefallen weil ich mal geschaut habe wie du bestimmte Sachen gelöst hast :)

was nun?

**Comment by DavidGuetl** [comment]
Eigentlich habe ich es so gemacht, dass die Einstellung beim hinzufügen einer Figur als vorauswahl dienen soll, aber als Speicherwert dann die Einstellung der Figure.

Oder bin ich da wo drübergestolpert?

**Comment by Catzenjaeger** [comment]
die FIGURE ITEMS sähe dann so aus:

```
		figure_allow_comments TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
		figure_allow_ratings TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',		
		figure_allow_videos TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
		figure_allow_affiliates TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
		figure_allow_amazon TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
		figure_allow_ebay TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',	
```

**Comment by DavidGuetl** [comment]
Nochmal Code eben überprüft, laut Code ist es sowie eben geschrieben 

Leeres Formular nutzt globale Einstellungen als Vorauswahl
Gepsiechert wird allerdings dann der Wert der Figur
Vorauswahl bei Bearbeiten ebenfalls Wert der Figure

**Comment by Catzenjaeger** [comment]
also müsstene nur noch die jetzt von mir himnzugerfügten sachen eingebaut werden????? 

also 

        figure_allow_videos TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
        figure_allow_affiliates TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
        figure_allow_amazon TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
        figure_allow_ebay TINYINT(1) UNSIGNED NOT NULL DEFAULT '1', 

coments und ratings waren ja schon drin

**Comment by DavidGuetl** [comment]
Ja weiss nicht warum du dass so machen wolltest :-o

Ja musst dann noch einfügen, aber bitte genauso verfahren wie ich.

**Comment by DavidGuetl** [comment]
Aber wozu die Angaben bei der Figur? Einfach die Felder leer lassen wer doch unsinnig

**Comment by Catzenjaeger** [comment]
wie meinst du das leer lassen?

**Comment by DavidGuetl** [comment]
Naja wozu willst du Checkboxes bei der Figur einfügen, lass doch einfach die Felder bei der Figur leer

**Comment by DavidGuetl** [comment]
Nein dass ist nur bei einem leeren Formular .. sind globale Einstellungen die Kommentare an, ist fass auch bei der Figure hinzufügen automatisch die vorauswahl .. ist es deaktiviert ist es beim figure hinzugefügen ebenso deaktiviert kann aber aktiviert werden

**Comment by Catzenjaeger** [comment]
theoretisch machbar allerdings habe ich die Darstellung der Figuren in Modulen von anfang an geplant. 
das ist im template - admin/template_render_figure_items.php ist auch so aufgebaut


- Bild Modul
- Daten Modul
- Affiliates Modul
- mycollecction Modul
- comments Modul
- ratings Modul
- social sharing Modul

**Comment by DavidGuetl** [comment]
Verstehe halt nicht genau was du als Problem siehst 😋

**Comment by Catzenjaeger** [comment]
naja du hast jetzt im neuen File das:
"figure_allow_comments" => $figurelibSettings['figure_allow_comments'],
 "figure_allow_ratings"  => $figurelibSettings['figure_allow_ratings'],

also holst du die settings beim laden aus der "lokalen" inf_seetings Tabelle.  muss da nicht 0 hin?
so wie in der  vorherigen version des files??

**Comment by DavidGuetl** [comment]
Nein dass ist ja egal, du wählst ja sowieso dann beim erstellen der figure

**Comment by Catzenjaeger** [comment]
und was ist wenn ich einen Figur editiere? oder ein Submit öffene? das greift ja auf die gleiche Form zu .. passt das dann?

**Comment by DavidGuetl** [comment]
Da wird das genommen was in der DB des Items gespeichert ist

**Comment by Catzenjaeger** [comment]
wann nimmt man

"figure_allow_comments_global"      	 => isset($_POST['figure_allow_comments_global']) ? 1 : 0,

und wann 

"figure_notification"         => form_sanitizer($_POST['figure_notification'],         1,    "figure_notification"),

**Comment by Catzenjaeger** [comment]
ich würde jetzt überall das so abändern damit man nicht durcheinander kommt. Wenn man mal später an den code muss würde man die zusammenhänge nicht mehr wissen.

deshalb würde ich vorschlagen alle allow dinge mit der endung global zu kennzeichen

das würde dann so aussehen:

Figure Setting --> DB FIGURE_ITEMS

figure_allow_images
figure_allow_data
figure_allow_videos
figure_allow_affiliates
figure_allow_amazon
figure_allow_ebay
figure_allow_comments
figure_allow_ratings
figure_allow_social_sharing	


Setting global --> DB Inf_Settings

figure_allow_images_global
figure_allow_data_global
figure_allow_videos_global
figure_allow_affiliate_global
figure_allow_amazon_global
figure_allow_ebay_global
figure_allow_comments_global
figure_allow_ratings_global
figure_allow_social_sharing_global	

wäre das besser und ok?

**Comment by DavidGuetl** [comment]
Ja wäre besser.

Den isset Check nimmt man bei Checkboxes,weil werden diese nicht gewählt,werden sie nicut gepostet und man wird geworfen

**Comment by Catzenjaeger** [comment]
also bei checkbo isset und bei dropdown das andere?

**Comment by DavidGuetl** [comment]
Jop

**Comment by Catzenjaeger** [comment]
ok danke .. wieder etwas gelernt :)
