### ISSUE TITLE
Frage  vorbelegung 

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#45]
ich muss da noch einmal kurz nachfragen

Das hier nimmt man für Checkboxen
figure_allow_comments_global" => isset($_POST['figure_allow_comments_global']) ? 1 : 0,

Das hier für Dropboxen
"figure_notification" => form_sanitizer($_POST['figure_notification'], 1, "figure_notification"),

Und wozu das hier? was sind da die unterscheide? 
"figure_editionsize"    		=> (isset($_POST['figure_editionsize']) ? form_sanitizer($_POST['figure_editionsize'],  "", "figure_editionsize") : ""),

dan gibts noch das
"figure_pubdate"        		=> stripinput(trim($_POST['figure_pubdate'])),

und das
"figure_description"    		=> addslash(nl2br(parseubb(stripinput($_POST['figure_description'])))),

oder gibts noch mehr?

**Comment by DavidGuetl** [comment]
Da gibts noch viel mehr ... stripslashes(), isNum(), str_replace(), parsesmileys(), ..

Überprüfung bei Checkboxen generell:
$meineBox = isset($_POST['meinebox']) ? 1 : 0;

Überprüfungen von Radioboxen:
$radiobox = stripinput(trim($_POST['radiobox']));

Überprüfung von Textboxen
$textbox = stripinput(trim($_POST['textbox']));

Bei Auswahllisten
$select = stripinput(trim($_POST['select']));

Wenn es sich um einen Zahlenwert handeln muss:
$feld = isNum($_POST['feld']) ? $_POST['feld'] : "0";

Bei Textareas:
addslash = Fügt Slashes ein, damit der Inhalt problemlos gespeichert werden kann.
stripslash = Entfernt die eingefügten Slashes wieder.
nl2br = Wandelt \n zu <br /> um (Zeilenumbrüche)
parseubb = Parst alle BB-Codes zu HTML.
parsesmileys = Parst die Smileys zu HTML - Img Tags.

Seit PHP-Fusion v9 nutzt man allerdings für fast alles den Form-Sanitizer .. allerdings ist der noch nicht so ganz auf den Beinen meiner Meinung nach ..

Deshlab bei Checkboxen die alte Version verwenden, bei Textareas je nach Inhalt ebenso.

Den Code bei editionssize ist bedingt dadurch, da wir ja das Feld nur bei einem Wert "aktiv" haben und bei den anderen nicht. Ist es nicht aktiv, wird es nicht mitgepostet. Deshalb zuvor die Überprüfung ob es gepostet wurde, und falls ja, dann den Inhalt.

**Comment by Catzenjaeger** [comment]
klasse danke das speichere ich mir mal irgendwo :)
wenn einen das niemand erklärt weiss man das auch nicht :) hehe
