### ISSUE TITLE
FRAGE: Ausgabe Datum umformatieren

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#47]
das 01.1992 meine ich . Könnte man das irgendwie so umstellen, dass die Ausgabe ein bisschen anders aussieht? zB 02/1992 oder FEB1992 oder FEB/1992

**Comment by DavidGuetl** [comment]
admin_figurelib .. schau dort mal bei dem Feld da kann man das einstellen.

**Comment by Catzenjaeger** [comment]
habe das von so

```
$('#figure_pubdate-field .input-group.date').datetimepicker({
		showTodayButton: true,
		showClear: true,
		showClose: true,
		allowInputToggle: true,
		format: 'MM.YYYY',
});
```

auf so format: 'MM/YYYY', 

zeigt sich aber keine Änderung

**Comment by DavidGuetl** [comment]
Musst ja auch mal eines aktualisieren also eine Einsendung dann sollts passen.

**Comment by Catzenjaeger** [comment]
achso das greift nur beim schreiben :) verstehe :)

**Comment by Catzenjaeger** [comment]
passt supi danke für die Lösung

**Comment by Catzenjaeger** [comment]
ich muss noch einmal aufgreifen. Generell funzt das .. aber kann man das auch so machen, dass in Panels was anderes angezeigt als im Text? weil momentan steht im Panel aus Platzgründen nur jan.... 
da sollte dann (02)1992 oder so und im normalen Text wo platz ist ausgeschrieben. Ginge das?

**Comment by DavidGuetl** [comment]
Ist möglich - Muss ich mir aber erst überlegen wie am besten ;)

**Comment by Catzenjaeger** [comment]
muss nicht unbedingt gleich sein ahbe es so gelöst: ich lass mir erst das Jahr ausgeben und dann den rest .. wenn ich dann trimme auf 6 Zeichen steht 1992.. da :) ist doch ok :)

**Comment by Catzenjaeger** [comment]
ich denke kann erstmal closed
