### ISSUE TITLE
SMALL ERROR Slideshow

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#48]
bei der Slideshow wird immer wenn das Bild wechselt die Seite verschoben. Heißt, wenn man gerade weiter unten auf der Seite ist lädt die neu und geht wieder nach oben. Der Fokus wird irgendwie falsch gesetzt oder so.

Mann gar nichts macht wandert die Seite mit jeden Bildwechsel immer weiter (also scrollt)

**Comment by Catzenjaeger** [comment]
https://github.com/Catzenjaeger/FigureLib_4/issues/51 siehe auch dort
die Pfeile sind wieder da bei einer Figur. Da die Bilder jetzt anders eingebunden sind -- gibts hier was zu beachten oder wo muss man ran?

**Comment by DavidGuetl** [comment]
Dass ist normal weil es ja eine Slideshow ist.

**Comment by Catzenjaeger** [comment]
sollte man vielleicht die automatische weiterschaltung lassen -- also carusell aus und bei klick wechseln lassen? Weil das wechseln stört massiv wenn ich zb einen Komentar schreibe und auf einmal die seite sich verschiebt .. das geht mal garnicht

**Comment by DavidGuetl** [comment]
Kannst schließen - Dank der fixen Höhe ist das Problem jetzt weg.

**Comment by Catzenjaeger** [comment]
:) :+1:
