### ISSUE TITLE
Error: last figures center panel

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#49]
beim Gaststatus wird das Zeichen nicht mehr angezeigt das nur für member verfügbar

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/17969632/58003380-6ad3-11e6-9e8a-079e5d54e0ea.JPG)

File: https://github.com/Catzenjaeger/FigureLib_4/blob/master/infusions/latest_figures_center_panel/latest_figures_center_panel.php

**Comment by DavidGuetl** [comment]
Die hier verlinkte Datei ist definitiv nicht die aktuelle ....

**Comment by Catzenjaeger** [comment]
das ist die aus deinen donloadpaket heute ... das kann nicht stimmen weil ich most clicked gar nicht mehr habe sondern der link nach stats geht.

**Comment by DavidGuetl** [comment]
Eig hab ich die neue genommen .. hm komisch . kannst die paar Änderungen auch so eintragen? :P

**Comment by Catzenjaeger** [comment]
hmnn was haste den so geändert? Bild Darstellung denke ich und das pubdate alles andere sollte ja gleich geblieben sein

**Comment by DavidGuetl** [comment]
Und die MyCollection ist nun als Funktion unterwegs :P

**Comment by Catzenjaeger** [comment]
?????

**Comment by DavidGuetl** [comment]
Dürftest du ja schon behoben haben, weil bei mir wird es angezeigt mit deinen Files, also # closed.

**Comment by Catzenjaeger** [comment]
ware mal bei dem file figure _items

ich bin da gerade dabei. schau mal hier: http://aliencollectors.com/test/infusions/figurelib/figures.php?figure_id=1

**Comment by DavidGuetl** [comment]
Warte .. schick sie dir gleich ^^

**Comment by DavidGuetl** [comment]
Kannst ja eig auch schließen, oder?
