### ISSUE TITLE
Idea: other icons

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#5]
in categories we have atm folder symbols. 
Is it possible this to change fast ?
example a figure icon :)

I mean here
![ashampoo_snap_2016 08 20_16h04m39s_026_](https://cloud.githubusercontent.com/assets/19621858/17831697/5558e7c6-66f0-11e6-927c-6e3286aa0edb.jpg)

**Comment by DavidGuetl** [comment]
Figure Icon -> Which Figure?

**Comment by Catzenjaeger** [comment]
![figurelib](https://cloud.githubusercontent.com/assets/19621858/17831757/36674590-66f2-11e6-8989-7a700cc59be2.png)
![default](https://cloud.githubusercontent.com/assets/19621858/17831758/4be5317a-66f2-11e6-89b8-94d082d281bb.gif)

or other egal

**Comment by DavidGuetl** [comment]
For all Categories the same Pic?

**Comment by Catzenjaeger** [comment]
what is your opinion?

**Comment by DavidGuetl** [comment]
Maybee Category Icons?

**Comment by Catzenjaeger** [comment]
sound good :)

**Comment by Catzenjaeger** [comment]
done
