### ISSUE TITLE
Error: was den jetzt apssiert admon_figurelib

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#50]
wollte gerade ein Figur adden und bekomme das: 

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/17970172/b84ecc36-6ad5-11e6-95d9-37d4aa615d65.JPG)

**Comment by Catzenjaeger** [comment]
jetzt habe ich das bestätigt und bekomme das:

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/17970208/e290391c-6ad5-11e6-913b-4458dfaa1c5e.JPG)

**Comment by DavidGuetl** [comment]
Oops da hab ich was vergessen zu entfernen :D :D 

Allerdings wenn kein Fehler im Formular auftritt ist alles normal, oder?

**Comment by Catzenjaeger** [comment]
ich probiere es nochmal

**Comment by Catzenjaeger** [comment]
der fehler tritt immer auf wenn ich was vergesse und oder beim fehlerhaften bilderupload. Heisst ich habe hier versucht ein zu großes bild hochzuladen

**Comment by DavidGuetl** [comment]
Jop, such dann gleich die Stelle und sags dir ..^^

**Comment by DavidGuetl** [comment]
Suche nach print_r($_POST); in admin_figurelib.php und entferne es.

**Comment by Catzenjaeger** [comment]
:) supi
