### ISSUE TITLE
Error: klick auf Bild in Slideshow zeigt "imagenotfound"

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#53]
in der slideshow wird bei klick auf das Bild dieses nicht geöffnet sondern das imagenotfound Bild
Außerdem soll das Bild in einen neuen Fenster erscheinen

**Comment by DavidGuetl** [comment]
# fixed

**Comment by Catzenjaeger** [comment]
:+1:  muss ich noch checken hehe
