### ISSUE TITLE
Error: wenn "add to collection" alle Panele darunter weg

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#56]
template_figure_items

**Comment by Catzenjaeger** [comment]
file ist hier https://github.com/Catzenjaeger/FigureLib_4/blob/master/infusions/figurelib/templates/template_render_figure_items.php

**Comment by DavidGuetl** [comment]
Hab das grad probiert, bei mir passt alles?

**Comment by Catzenjaeger** [comment]
hmn bei mir nicht -- aber du brauchst alle dateien .. habe sehr viel eingebaut .. die g
![ashampoo_snap_2016 08 25_22h59m27s_001_](https://cloud.githubusercontent.com/assets/19621858/17985762/8d601c36-6b17-11e6-8c7e-63e3c61ae51f.jpg)
anzen menue

**Comment by Catzenjaeger** [comment]
Unter add/remove to coleection fehlt alles .. aber nur wenn ich die figur geadded habe. wenn ich sie wider lösche erscheint auch das andere wieder
![ashampoo_snap_2016 08 25_23h10m02s_002_](https://cloud.githubusercontent.com/assets/19621858/17986059/23ae414e-6b19-11e6-80d2-d350148666d8.jpg)

**Comment by DavidGuetl** [comment]
Huch tatsächlich 😂

**Comment by DavidGuetl** [comment]
#fixed

**Comment by Catzenjaeger** [comment]
Hola was haste den geändert - weil ich muss das noch fertig umbauen wegen bootstrap -- ich habe alle tabellen usw rausgeschmissen damit perfekt auf allen geräten funktioniert

**Comment by Catzenjaeger** [comment]
ok ich baue alles noch mal neu ein .. Habe auch paar locale die hardcoded waren ersetzt. Das mach ich jetzt
