### ISSUE TITLE
Schönheitsfehler: Slideshow

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#57]
wenn verscheidende Bildformate dann switcht der Kasten auch von groß auf klein in der Größe. Kann man das fix machen?

**Comment by DavidGuetl** [comment]
Jop habs dir mal auf 400px gestellt (kannst in der tempalte-Datei ändern).

**Comment by Catzenjaeger** [comment]
:+1:
