### ISSUE TITLE
Frage: Bilder verschiebbar?

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#58]
geht das? also so man die Bilder in der reihen folge ändern kann. Das wäre cool wenn das admins könnten ... sie könnten dann nämlich das beste Bild als Titelbild nehmen. Weil könnte durchaus sein das die Bodenplatte der Fir sonst das Titelbild ist :)

**Comment by DavidGuetl** [comment]
Vorschlag meinerseits: Im Adminbereich bei den Figuren bei den Bildern Radioboxen wo der Admin auswählen kann: "Dieses Bild als erstes Bild verwenden", würde ja reichen oder? Weil alle zu sortieren wird aufwendig :o

**Comment by Catzenjaeger** [comment]
lol das wäre oberhammer ... :)

**Comment by DavidGuetl** [comment]
Füge mal in die Image-DB folgendes ein:
figure_images_toppic tinyint(1) UNSIGNED NOT NULL DEFAULT '0'

**Comment by Catzenjaeger** [comment]
habe ich gemacht .. .. ah verstehe .. coole Idee :)

**Comment by Catzenjaeger** [comment]
coole sache :) 
wenn der admin das machen kann ist ok. Nur muss der admin auch immer dann schauen .. aber damit kann man leben denke ich oder? 

Beim hochladen geht das eh nicht denke ich wäre zu kompliziert

**Comment by DavidGuetl** [comment]
Nope, da es sich ja um Multi Upload etc handelt - das würde meiner Meinung garnicht gehen ..^^

**Comment by Catzenjaeger** [comment]
ok reicht ja auch :)
