### ISSUE TITLE
ERROR: submit funktioniert nocht nicht

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#63]
habe schon probiert aber da ist zuviel was nicht mehr geht

**Comment by DavidGuetl** [comment]
Ab Morgen schon 😋

**Comment by DavidGuetl** [comment]
# fixed

**Comment by Catzenjaeger** [comment]
submit geht aber es wird eine notice in den log geschrieben

figurelib/submit.php
/test/infusions/figurelib/submit.php?stype=f
Undefined index: figure_id
Line: 504 

siehe hier: https://github.com/Catzenjaeger/FigureLib_4/issues/75
