### ISSUE TITLE
ERROR: Länder stimmen nicht mit Eingabe überein

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#65]
habe 4 Figuren angelegt und bei allen sind die Länder falsch angezeigt. 
im Editbereich stimmen aber nicht auf der item - ich glaube das liegt am zusätzlich unknown

**Comment by DavidGuetl** [comment]
Hast du Recht is schnell behoben

**Comment by DavidGuetl** [comment]
#fixed

**Comment by Catzenjaeger** [comment]
cool :)

**Comment by Catzenjaeger** [comment]
klasse funzt so wie es aussieht :)
