### ISSUE TITLE
Remove function - popup/notice missing

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#66]
wenn jemand die figur von seiner collection löschen tut sollte noch einen abfrage kommen .. mir ist schon paarmal passiert das ich ausversehen eine gelöscht habe

**Comment by DavidGuetl** [comment]
Baue ich mit ein, ist easy

**Comment by DavidGuetl** [comment]
# fixed

**Comment by Catzenjaeger** [comment]
coooooll das baue ich noch bei adden auch noch ein :) 
kann man das auch anders .. also farbig gestalten? Passend zur seite

**Comment by Catzenjaeger** [comment]
kann aber closed da im Prinzip funzt
