### ISSUE TITLE
ERROR: BB Button Funktion in add_figure keine Funktion

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#69]
die Buttons gehen nicht

![ashampoo_snap_2016 08 28_10h32m24s_014_](https://cloud.githubusercontent.com/assets/19621858/18032627/a3a0fa02-6d0a-11e6-9ba8-4f646ef7ae02.jpg)

**Comment by DavidGuetl** [comment]
Kleiner Fehler behebe ich

**Comment by DavidGuetl** [comment]
# fixed

**Comment by Catzenjaeger** [comment]
danke funzt :)
