### ISSUE TITLE
Improvement: submit.php (Measurements)

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#7]
normally i had here 2 fields (inch + centimeter)
I have not found a compromise that may be notified as user which unit he tells us. How could you do that? Specification in inch or centimeter

in infusion.php i had this but in final version only inch field (all other is to complicated for me hehe)

Give it here a better solution?

`$inf_insertdbrow[] = DB_FIGURE_MEASUREMENTS." (figure_measurements_id, figure_measurements_inch, figure_measurements_cm, figure_measurements_description, figure_measurements_sorting) VALUES 
(1, 'Unknown','', '', 'figure_id ASC'),
(2, '01 Inch','2,54 cm', '', 'figure_id ASC'),
(3, '02 Inch','5,08 cm', '', 'figure_id ASC'),
(4, '03 Inch','7,62 cm', '', 'figure_id ASC'),
(5, '04 Inch','9,00 cm', '', 'figure_id ASC'),
(6, '05 Inch','12,70 cm', '', 'figure_id ASC'),
(7, '06 Inch','15,24 cm', '', 'figure_id ASC'),
(8, '07 Inch','17,78 cm', '', 'figure_id ASC'),
(9, '08 Inch','20,32 cm', '', 'figure_id ASC'),
(10, '09 Inch','22,86 cm', '', 'figure_id ASC'),
(11, '10 Inch','25,40 cm', '', 'figure_id ASC'),
(12, '11 Inch','27,94 cm', '', 'figure_id ASC'),
(13, '12 Inch','30,48 cm', '', 'figure_id ASC'),
(14, '13 Inch','33,02 cm', '', 'figure_id ASC'),
(15, '14 Inch','35,56 cm', '', 'figure_id ASC'),
(16, '15 Inch','38,10 cm', '', 'figure_id ASC'),
(17, '16 Inch','40,64 cm', '', 'figure_id ASC'),
(18, '17 Inch','43,18 cm', '', 'figure_id ASC'),
(19, '18 Inch','45,72 cm', '', 'figure_id ASC'),
(20, '19 Inch','48,26 cm', '', 'figure_id ASC'),
(21, '20 Inch','50,80 cm', '', 'figure_id ASC'),
(22, '21 Inch','53,34 cm', '', 'figure_id ASC'),
(23, '22 Inch','55,88 cm', '', 'figure_id ASC'),
(24, '23 Inch','58,42 cm', '', 'figure_id ASC'),
(25, '24 Inch','60,96 cm', '', 'figure_id ASC'),
(26, '25 Inch','63,50 cm', '', 'figure_id ASC'),
(27, '26 Inch','66,04 cm', '', 'figure_id ASC'),
(28, '27 Inch','68,58 cm', '', 'figure_id ASC'),
(29, '28 Inch','71,12 cm', '', 'figure_id ASC'),
(30, '29 Inch','73,66 cm', '', 'figure_id ASC'),
(31, '30 Inch','76,20 cm', '', 'figure_id ASC'),
(32, 'bigger than 30 Inch','76,20 cm', '', 'figure_id ASC')`

**Comment by DavidGuetl** [comment]
Man Suche:
`DB_FIGURE_MEASUREMENTS, "figure_measurements_inch", "figure_measurements_id", "figure_measurements_parent");`

Man ersetzte durch:
`DB_FIGURE_MEASUREMENTS, "".(LANGUAGE == "English" ? "figure_measurements_inch" : "figure_measurements_cm")."", "figure_measurements_id", "figure_measurements_parent");`

**Comment by Catzenjaeger** [comment]
Hmn geht leider nicht .. habe das 3 mal im code (höhe breite tiefe)

hier der code eines feldes aus der submit.php

`		DB_FIGURE_MEASUREMENTS, "figure_measurements_inch", "figure_measurements_id", "figure_measurements_parent");
		// Select Field "Depth"
		echo form_select_tree("figure_depth", $locale['figure_446'], $submitdata['figure_depth'], 
			array(
				"inline" => TRUE,
				"required" => TRUE,
				"width" => "400px",
				"placeholder" => $locale['figurelib-placeholder-107'],
				"error_text" => $locale['figurelib-error-105'],
				"no_root" => 1,
				"query" => (multilang_table("FI") ? "WHERE figure_measurements_language='".LANGUAGE."'" : ""),
				"maxselect" => 1,
				"allowclear" => TRUE,
			),
		DB_FIGURE_MEASUREMENTS, "figure_measurements_inch", "figure_measurements_id", "figure_measurements_parent");`

**Comment by DavidGuetl** [comment]
Siehe Issue betreffend Limitation

**Comment by Catzenjaeger** [comment]
aber cm ist nirgends zu sehen?

**Comment by DavidGuetl** [comment]
Ohja, wenn du die Seitensprache zb. auf Deutsch stellst, dass wolltest du ja, oder?

**Comment by Catzenjaeger** [comment]
hmnnn auf der einen seite ja auf der anderen nicht:

momentan habe ich nur english. Wenn ich auch deutsch mache würde der inhalt NUR für deutsche sichtbar .. das ist ja das dooffe an version 9. Deshalb ist deinen version eigentlich richtig ... ich hatte das eher gedacht das man praktisch beides auswählen kann bzw zugleich sieht damit auch ein deutscher was damit anfangen kann. Ich denke die meisten wissen nämlich nicht wieviel ch 12 inch sind :)

ich hatte das ursprunflich mal so:

12 Inch (30 Zentimeter) -- da swollte ich so im dropdown. eingetragen wird aber nur inch damit man ein Standard wert hat. Genau das gleiche wäre bei gramm und kilogramm auch notwendig

**Comment by DavidGuetl** [comment]
Was haltest davon wenn du die Einträge einfach bearbeitest und dass so speicherst in die DB: xx Inch (xx Zentimeter) ?

Dann brauchst du nicht kompliziert rumändern oder dergleichen (meiner Meinung nach).

**Comment by Catzenjaeger** [comment]
das hatte ich doch zu aller erst so :) 
habs dann getrennt und umgebaut.
dachte nur es geht auch so das man beide spalten gleichzeitig einblendet und synchronisiert

**Comment by DavidGuetl** [comment]
Leider nein .. :-/ Dafür ist die PHP-Fusion Funktion nicht ausgelegt (was im Regelfall auch nicht gebraucht wird) weil man dass ja normal Sprachabhängig steuert :P

**Comment by Catzenjaeger** [comment]
dann ändere ich die Beschreibung der felder -- das ist am einfachsten denke ich
also zurück zum Ursprung :)

**Comment by DavidGuetl** [comment]
Genau ;)

**Comment by Catzenjaeger** [comment]
ok mache ich :)
closed
