### ISSUE TITLE
Small Error: im Editbereich klick aufs Bild markiert es als zu löschen - besser wäre als titelbild

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#70]
![ashampoo_snap_2016 08 28_10h39m50s_015_](https://cloud.githubusercontent.com/assets/19621858/18032650/b360b882-6d0b-11e6-9f9f-6dda83cb913a.jpg)

**Comment by DavidGuetl** [comment]
Mach ich ist nicht viel

**Comment by DavidGuetl** [comment]
# fixed

**Comment by Catzenjaeger** [comment]
danke funzt
