### ISSUE TITLE
was hälst du davon + Frage

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#71]
habe gerade ien neues adminpanel geschrieben und würde das gerne per infuse gleich installieren lassen 

ich suche daher die passenden werte hierfür

manches weiss ich aber nicht alles -- wo gibt es die erklärung dazu welche weerte möglich sind 

`$inf_insertdbrow[] = DB_PANELS." (
						panel_name, 
						panel_filename, 
						panel_content, 
						panel_side, 
						panel_order, 
						panel_type, 
						panel_access, 
						panel_display, 
						panel_status, 
						panel_url_list, 
						panel_restriction
						) VALUES(
						'Figurelib Admin panel', 
						'figurelib_admin_panel', 
						'', 
						'2', 
						'2', 
						'file', 
						'0', 
						'1', 
						'1', 
						'', 
						'3'
						)";	`

so siehts aus :) 
![ashampoo_snap_2016 08 28_20h46m36s_016_](https://cloud.githubusercontent.com/assets/19621858/18035936/abb3f55e-6d60-11e6-8091-3f1de4269683.jpg)
0
wenn submissions rein kommen sollte hinter submissions ein rotes badge zu sehen sein ... kann es nicht testen da szbmit nicht geht :)

**Comment by DavidGuetl** [comment]
Sende dir morgen auf deiner Seite einen Link zu der Erklärung.

Betreffend Submit mache ich morgen - Aber brauchst ja theoretisch nur die aus dem Admin nehmen von mir.

**Comment by Catzenjaeger** [comment]
in den neuen files die ich dir noch schicke ist das alles schon drin
ich sende dir das jetzt schnell da ich heute nichts mehr mache -- heute ist spieleabend - Unreal Torunament :)

**Comment by DavidGuetl** [comment]
Hehehe Ok :-)

**Comment by Catzenjaeger** [comment]
da müssen noch einige settings anders gemacht werden .. habe es gerade auf deiner Seite gesehen das Ding ist für Besucher sichtbar . Soll nicht sein nur für admins. Weiterhin soll es an erster stelle links oben sein

**Comment by Catzenjaeger** [comment]
die datenbank von dir ist Hammer :) danke

**Comment by Catzenjaeger** [comment]
funzt :) 
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18045937/b3ef6c88-6dd5-11e6-9da7-f4ed1f9a27f1.JPG)
