### ISSUE TITLE
Frage: kann man Hinweis schalten beim Bildupload bzw wenn man da draufklickt

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#72]
da ich bissel angst habe das jemand copyright geschützte Bilder oder geklaute oder einfach nur welche von google suche nimmt wollte ich fragen ob man da einen Hinweis schalten kann mit einem Text.

also wenn er in submit auf bildupload klickt. Quasi als Hinweis

unten die AGB muss er eh bestätugen

**Comment by DavidGuetl** [comment]
http://test.phpfusion-pro.com/infusions/figurelib/submit.php?stype=f meinst so?

**Comment by Catzenjaeger** [comment]
JA GEILLLLLLL

**Comment by DavidGuetl** [comment]
Hast du die Mail bekommen?

**Comment by Catzenjaeger** [comment]
hmmn welche habe viele ;) geht habs probiert  -- vielleicht sollte dort auch der link zur agb dann drin sein

**Comment by Catzenjaeger** [comment]
habe das eingefügt das geht aber nicht

$(function() {
    $('input[name=\"figure_videourl[]\"]').click(function(){
        return confirm('Please note, that all Videos must be Copyright Free!');
    });
});

weitere frage wenn das Feld video leer ist wird standardmäßig angezeigt:  
Sorry! There is no Video avaible to this Figure.


müsste da nicht stehen klicken sie hier um einen vorschau zu sehen?

**Comment by DavidGuetl** [comment]
Welche Vorschau wenn nicht mal eines vorhanden ist?

**Comment by Catzenjaeger** [comment]
nun ja, wenn man das submit öffnet steht gleich da kein Preview vorhanden. Um dieses Feld aber überhaupt zu aktivieren muss man erst einmal rein klicken. Wenn man nicht klickt wird auch nichts angezeigt. selbst wenn oben eine emded Code drin steht

**Comment by DavidGuetl** [comment]
Also habe die Hinweis Nachricht nun gefixxt.

Dass wenn ein Embed angegeben wurde nicht das Video angezeigt wird kann ich nicht nachvollziehen.

**Comment by Catzenjaeger** [comment]
ok habs gesehen :) danke :+1:
