### ISSUE TITLE
submit felder alle gleichlang ohne die länge anzugeben

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#73]
ich habe das immer mit dem Kriterium width gemacht was auch geht . Aber dann ist das wieder auf diversen geräten nicht komform wegen botstrap. wie kann ich die Felder alle gleich lang bekommen

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18043369/af661d64-6dc7-11e6-986b-8548b7df5061.JPG)

**Comment by DavidGuetl** [comment]
Vllt mit width: 100% aber habs nicht probiert

**Comment by Catzenjaeger** [comment]
lol geht sogar .. aber was ist dann auf gr0ßen Bildschirmen .. dann wird das ein Meter lang ... gibt es ein Kompromiss? wir würdest du das machen?

**Comment by DavidGuetl** [comment]
Sollten eigentlich maximal bis am Inhaltsrand gehen 😊

**Comment by Catzenjaeger** [comment]
also ich habe es auf 100% uns sieht gut aus .. alles schön gleichlang :) handy und tablet weiss ich nicht
http://aliencollectors.com/test/infusions/figurelib/submit.php?stype=f

**Comment by DavidGuetl** [comment]
Handy passt ;-)

**Comment by Catzenjaeger** [comment]
danke :+1:
