### ISSUE TITLE
Undefined index: figure_id

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#75]
Error	Options	Severity	Status
figurelib/submit.php
/test/infusions/figurelib/submit.php?stype=f
Undefined variable: formFailure
Line: 160

Run-time notices 	
figurelib/submit.php
/test/infusions/figurelib/submit.php?stype=f
Undefined index: figure_language
Line: 86

Run-time notices 	
figurelib/submit.php
/test/infusions/figurelib/submit.php?stype=f
Undefined index: figure_id
Line: 505

Run-time notices 	
figurelib/submit.php
/test/infusions/figurelib/submit.php?stype=f
Undefined index: figure_id
Line: 502

**Comment by DavidGuetl** [comment]
# fixed

**Comment by Catzenjaeger** [comment]
danke glaub dir das :) :+1:
