### ISSUE TITLE
BUG???: Textfelder Discreption usw. kein "ziehen" möglich nur nach rechts aber nicht nach unten

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#76]
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18045603/ef5defda-6dd3-11e6-8ca3-daaa5c008fc1.JPG)

**Comment by DavidGuetl** [comment]
# fixed in submit.php

**Comment by Catzenjaeger** [comment]
muss das in anderen Dateien auch gefixt werden?

**Comment by DavidGuetl** [comment]
Ja es muss nur "autosize" => true entfernt werden müssen.

**Comment by Catzenjaeger** [comment]
supi danke
