### ISSUE TITLE
Frage - wo wird denn das popup generiert bei submit  Bilderupload

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#77]
wollte das gleiche auch für die Videos 

wo wird denn das gemacht? Im submit und in function war nichts zu finden .-- bin ich blind

**Comment by DavidGuetl** [comment]
Submit.php ganz unten bei jQuery :-)

**Comment by Catzenjaeger** [comment]
haste gerade reingemacht :) nene sorry überlesen
