### ISSUE TITLE
Schau mal - komplett redesignend :) + Frage

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#78]
nur einen Frage ... wie könnte ich Speichergröße des Ordner auslesen.
So hätte man als Admin schnelle Übersicht 

![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18048848/eb470100-6de4-11e6-8c87-49e4f61f7874.JPG)

**Comment by DavidGuetl** [comment]
Uff dass müsstest du googlen, dass weiss ich nicht.

**Comment by Catzenjaeger** [comment]
ok ist auch nicht sooo wichtig -- Hauptsache erstmal keine fehler
deshalb mache ich das zu
