### ISSUE TITLE
Panel Access:  werte wo finde ich dei? 1/2/3 geht nicht war das 102 usw?

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#79]

**Comment by DavidGuetl** [comment]
-101 Mitglieder
-102 Admin
-103 Site Admin

**Comment by Catzenjaeger** [comment]
das fehlt in deiner DB -- mach das mit rein ist wichtig :) ansonsten ist das Ding Hammer ... so was habe ich immer gesucht -- musst nur was bei 9 rein tun :)
