### ISSUE TITLE
Frage: Edit Button in openside integriert

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#80]
mein versuch der nicht geht

			openside(".global $aidlink;
						if (iADMIN || iSUPERADMIN) {."		
							echo "<div class='alert alert-default'><i class='fa fa-bolt fa-vtop'></i>\n".$locale['figure_1822b']." <a href='".INFUSIONS."figurelib/admin.php".$aidlink."&amp;section=figurelib_settings'>".$locale['mc_0012']."</a></div>";

						".}.");

**Comment by DavidGuetl** [comment]
```
$editlink = "";
if (iADMIN || iSUPERADMIN) {
  $editlink = "editlink";
}
openside($editlink);
```

**Comment by Catzenjaeger** [comment]
lol auf diese Idee bin ich nicht gekommen :) danke
