### ISSUE TITLE
Error: submit.php -->  submitter fehlt

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#81]
da war vorher ein hidden feld drin .. soll das wieder rein?

**Comment by DavidGuetl** [comment]
Muss ich mir erst anschauen ..^^

**Comment by DavidGuetl** [comment]
# fixed

**Comment by Catzenjaeger** [comment]
Danke :)  :+1: 

muss da kein hidden field hin ?? scheint ja zu funzen
