### ISSUE TITLE
Error: Array to string conversion in figurelib_manufacturers

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#84]
Fehler tritt auf beim Aktualisieren eines Manufakturers

includes/sqlhandler.inc.php
/test/infusions/figurelib/admin.php?aid=c6b999cc59ff23ad&section=figurelib_manufacturers&action=edit&manufacturer_id=75
Array to string conversion
Line: 726

Source code (Line: 716 - 736)
716 	        return FALSE;
717 	    }
718 	
719 	    $sqlPatterns = array(
720 	        'save' => 'INSERT INTO `{table}` SET {values}',
721 	        'update' => 'UPDATE `{table}` SET {values} WHERE {where}',
722 	        'delete' => 'DELETE FROM `{table}` WHERE {where}'
723 	    );
724 	
725 	    foreach ($data as $name => $value) {
726 	        $sanitized_input[] = "`$name` = '$value'";
Line 726 -- 11 seconds ago
Array to string conversion
727 	    }
728 	
729 	    if (!isset($sqlPatterns[$mode])) {
730 	        // TODO Replace die with something better. I kept the old way (Rimelek)
731 	        die();
732 	    }
733 	    $where = '';
734 	
735 	    if ($mode === 'update' or $mode === 'delete') {
736 	        $pkwhere = array();
737

**Comment by Catzenjaeger** [comment]
das scheint mit dem Bild zusammen zu hängen
habe gerade ein Manufacturer geändert und da war die Mail falsch .. Form blieb stehen aber das Bild war nicht mehr zu sehen sondern nur ein Platzhalterbild

diese Meldungen kommen:

admin/admin_figurelib_manufacturers.php
/test/infusions/figurelib/admin.php?aid=a98b737f1d0fc5ac&section=figurelib_manufacturers&action=edit&manufacturer_id=75
Undefined index: thumb1_name
Line: 135
32 seconds ago 	
Run-time notices 	
admin/admin_figurelib_manufacturers.php
/test/infusions/figurelib/admin.php?aid=a98b737f1d0fc5ac&section=figurelib_manufacturers&action=edit&manufacturer_id=75
Undefined index: error
Line: 132
32 seconds ago 	
Run-time notices 	
admin/admin_figurelib_manufacturers.php
/test/infusions/figurelib/admin.php?aid=a98b737f1d0fc5ac&section=figurelib_manufacturers&action=edit&manufacturer_id=75
Undefined index: image_name
Line: 134

**Comment by DavidGuetl** [comment]
Jop liegt am Bild, selbe Fehler wird auch in der categories sein.

**Comment by Catzenjaeger** [comment]
ja so ist es ;(

**Comment by Catzenjaeger** [comment]
kann es daran liegen? da steht thumb1 !!!

		if (isset($_FILES['figure_manufacturer_file']) && $_FILES['figure_manufacturer_file']['name']) {
			if (!empty($_FILES['figure_manufacturer_file']) && is_uploaded_file($_FILES['figure_manufacturer_file']['tmp_name'])) {
				$upload = form_sanitizer($_FILES['figure_manufacturer_file'], "", "figure_manufacturer_file");
				if ($upload['error'] == 0) {
					figures_deleteImages("manufacturers", $data['figure_manufacturer_id']);
					$data['figure_manufacturer_image'] = $upload['image_name'];
					$data['figure_manufacturer_thumb'] = $upload['thumb1_name'];
				}
			}
		}

in der function aber nicht da steht nut thumb ... weiss nicht ob das eine  rolle spielt

**Comment by DavidGuetl** [comment]
Das sollte an den folgenden Zeilen liegen (Manufacturer):
Suche:
```
$data['figure_manufacturer_image'] = dbarraynum(dbquery("SELECT figure_manufacturer_image FROM ".DB_FIGURE_MANUFACTURERS." WHERE figure_manufacturer_id='".$data['figure_manufacturer_id']."' LIMIT 0,1"));
$data['figure_manufacturer_thumb'] = dbarraynum(dbquery("SELECT figure_manufacturer_thumb FROM ".DB_FIGURE_MANUFACTURERS." WHERE figure_manufacturer_id='".$data['figure_manufacturer_id']."' LIMIT 0,1"));
```

Ersetzte durch:
```
@list($data['figure_manufacturer_image']) = dbarraynum(dbquery("SELECT figure_manufacturer_image FROM ".DB_FIGURE_MANUFACTURERS." WHERE figure_manufacturer_id='".$data['figure_manufacturer_id']."' LIMIT 0,1"));
@list($data['figure_manufacturer_thumb']) = dbarraynum(dbquery("SELECT figure_manufacturer_thumb FROM ".DB_FIGURE_MANUFACTURERS." WHERE figure_manufacturer_id='".$data['figure_manufacturer_id']."' LIMIT 0,1"));
```


Bei den Kategorien, ebenfalls so ..
Suche:
```
$data['figure_cat_image'] = dbarraynum(dbquery("SELECT figure_cat_image FROM ".DB_FIGURE_CATS." WHERE figure_cat_id='".$data['figure_cat_id']."' LIMIT 0,1"));
$data['figure_cat_thumb'] = dbarraynum(dbquery("SELECT figure_cat_thumb FROM ".DB_FIGURE_CATS." WHERE figure_cat_id='".$data['figure_cat_id']."' LIMIT 0,1"));
```

Ersetzte durch:
```
@list($data['figure_cat_image']) = dbarraynum(dbquery("SELECT figure_cat_image FROM ".DB_FIGURE_CATS." WHERE figure_cat_id='".$data['figure_cat_id']."' LIMIT 0,1"));
@list($data['figure_cat_thumb']) = dbarraynum(dbquery("SELECT figure_cat_thumb FROM ".DB_FIGURE_CATS." WHERE figure_cat_id='".$data['figure_cat_id']."' LIMIT 0,1"));
```

**Comment by Catzenjaeger** [comment]
schein ok zu sein ich muss erstmal beobachten danke schon einmal

**Comment by Catzenjaeger** [comment]
ich denke das ist ok läuft kein fehler mehr auf :+1:
