### ISSUE TITLE
Error: submit.php

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#85]
figurelib/submit.php
/test/infusions/figurelib/submit.php?stype=f
Undefined index: figure_language
Line: 86

Run-time notices 	
figurelib/submit.php
/test/infusions/figurelib/submit.php?stype=f
Undefined variable: formFailure
Line: 160

Run-time notices 	
figurelib/submit.php
/test/infusions/figurelib/submit.php?stype=f
Undefined index: figure_id
Line: 504

**Comment by DavidGuetl** [comment]
# fixed

**Comment by Catzenjaeger** [comment]
sieht klasse aus von den beiden Einsendungen hat keine einen Fehler geworfen :)
