### ISSUE TITLE
FRage only warum manchmal formname und manchmal nicht

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#87]
hier zB 

	// Manufacturer Description							 
	echo form_textarea("figure_manufacturer_description", $locale['figm_0002'], $data['figure_manufacturer_description'], [
		"inline"    => true,
		"html"      => true,
		"preview"   => false,
		"autosize"  => true,
		"form_name" => "addmanufacturer"
	]);

da steht der form_name
aber das steht nicht bei allen Feldern .. hat das einen Grund?

**Comment by DavidGuetl** [comment]
Jap, muss man angeben damit die BBCodes korrekt funktionieren.

**Comment by Catzenjaeger** [comment]
alles klar danke :+1:
