### ISSUE TITLE
Frage: zusatzmodul eingebaut wird aber immer pro figur angezeigt . weiss nicht wie ich das ändern soll

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#88]
habe in der template_render_figure.php Datei "Manufacturer infos" eingebaut. 
Funzt super  ....  aber dort habe ich 2 Fehler:

Datei: https://github.com/Catzenjaeger/FigureLib_4/blob/master/infusions/figurelib/templates/template_render_figure.php

1.) Die Manufacturer Infos werden  immer pro Figur angezeigt --> hier live --> http://aliencollectors.com/test/infusions/figurelib/figures.php?figure_cat_id=2&figure_manufacturer=75
wenn ich es wo anders hinsetze wird nichts angezeigt oder auch alles verschoben. Ihc muss die richtige stelle finden .. gelinkt mir aber nicht
2.) unten ist immer ein Buchstabe zu sehen in der rechten unteren Ecke. Der ist auch nicht immer gleich weiss aber nicht wo der herkommt

**Comment by Catzenjaeger** [comment]
so sieht das aus: 
![unbenannt](https://cloud.githubusercontent.com/assets/19621858/18089479/7fc39b6e-6ec0-11e6-8e9c-8daef5f20923.JPG)

**Comment by DavidGuetl** [comment]
Soll dass nur einmal drüber angezeigt werden oder wie?

**Comment by Catzenjaeger** [comment]
ja einmal oben und unten drunter sollen die figuren immer angezeigt werden

**Comment by Catzenjaeger** [comment]
im Listenmodus übrigens gehts es ! genau so soll es sein

![ashampoo_snap_2016 08 30_18h38m50s_001_](https://cloud.githubusercontent.com/assets/19621858/18098102/01fa7bd2-6ee1-11e6-8a97-d7318f26f1bf.jpg)

**Comment by DavidGuetl** [comment]
Wieso? Ist ja eig immer der selbe Hersteller?

**Comment by Catzenjaeger** [comment]
bei  mir siehts anders aus :O

**Comment by Catzenjaeger** [comment]
aber der Fehler mit den Buchstaben/ziffer in der Ecke ist nicht zu sehen

**Comment by Catzenjaeger** [comment]
ich habe das jetzt halb lösen können .. ich habe einfach eine neue Abfrage obedrüber gemacht so das sich diese beiden DB Abfragen nicht ins Gehege kommen.

Aber die Page Nav funktioniert nicht. Könntest du da mal schauen bitte? 

code der datei ist hier: https://github.com/Catzenjaeger/FigureLib_4/blob/master/infusions/figurelib/templates/template_render_figure.php

live siehst du es hier: http://aliencollectors.com/test/infusions/figurelib/figures.php?figure_cat_id=2&figure_manufacturer=75
