### ISSUE TITLE
Idea: submit.php (Limitation)

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#9]
i have a filed for limitation yes or no.
in the next row i ask for number of limitation.

is it possible to make this field not writable when limitation = no?
problem it must be in "Echtzeit" 

![ashampoo_snap_2016 08 20_16h51m00s_029_](https://cloud.githubusercontent.com/assets/19621858/17831888/74c07e98-66f6-11e6-839b-aa1ec9681f94.jpg)

**Comment by DavidGuetl** [comment]
Einfach in die submit.php folgenden Javascript Code einfügen
```
// Add jQuery
		add_to_footer("
		<script type='text/javascript'>
		$(function(){
			$('#figure_limitation').change(function(){
				if ($(this).val() == 3 ) {
					$('#figure_editionsize').prop('disabled', true);
				} else {
					$('#figure_editionsize').prop('disabled', false);
				}
			});
		});
		</script>");
```

**Comment by Catzenjaeger** [comment]
hmn das feld ist nicht zu sehen und auch wenn ich ausfülle und auf absenden drücke kommt kein hinweis .. falsche stelle eingebaut? ich habe das ganz oben im file

**Comment by DavidGuetl** [comment]
Lad mir mal die aktuelle submit.php ins Github, dann baue ich dir dass rein. inklusive der Landauswahl.

**Comment by Catzenjaeger** [comment]
submit ist aktuell ... danke :) 
https://github.com/Catzenjaeger/FigureLib_4/blob/master/infusions/figurelib/submit.php

**Comment by Catzenjaeger** [comment]
Falls es nicht auf Tablets und Smartphones geht (kann es gerade nicht testen) gäbe es einen Alternative? 
Weil ich habe viele die Tablets und Smartphones nutzen (so wie ich auch) und es wäre fatal wenn da ein graues Feld wäre

**Comment by DavidGuetl** [comment]
Arm Smartphone funzt es genauso wie am PC; gerade getestet auf meinem Samsung Galaxy S7 Edge.

**Comment by Catzenjaeger** [comment]
ist eigentlich fertig oder? closed

hmnn das muss aber auch in die form des Admin-bereichs!

**Comment by DavidGuetl** [comment]
Kannst ruhig schließen dass merk ich mir 😁

**Comment by Catzenjaeger** [comment]
ok aber net vergessen :) LOL
