### ISSUE TITLE
Error: submit??? 

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#90]
templates/template_render_figure.php
/test/infusions/figurelib/figures.php?figure_cat_id=2&figure_manufacturer=75
Illegal string offset 'page_nav'
Line: 269
1 minute ago

habe 2 figuren zum test eingesendet und das war im log

**Comment by Catzenjaeger** [comment]
das soll das hier sein: 

echo $info['page_nav'] ? "<div class='text-right'>".$info['page_nav']."</div>" : '';

**Comment by DavidGuetl** [comment]
Also an der submit.php liegt das definitiv nicht, eher figures.php

**Comment by Catzenjaeger** [comment]
ok dann mach ich das zu
ich denke das kann eigentlich nur figure.php und template_render_figure.php sein .. wärst du so leib und schaust dir beide mal an?
