### ISSUE TITLE
Logikfehler: wenn figure auf freigabe=0 taucht das als submit in der liste wieder auf.

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#91]
weiss gar nicht ob das schon immer so war. Wenn man eine Figure editiert und auf Status Show on page af disabled stellt läuft die wieder unter submitts auf.

**Comment by Catzenjaeger** [comment]
eigentlich logisch das die auflaufen weil wir suchen ja in den submissions alle die figure_freigae=0 haben. Wenn ich nun eine Figur  editiere und dort "show on page" ändere setze ich ja den DB Eintrag wieder auf 0 so das diese Figur wieder in den submitts aufläuft. 

hast du einen Idee?

**Comment by DavidGuetl** [comment]
Also seit ich dir helfe war das schon immer so.

Ja man könnte auf Status 2 oder dergliechen setzen, müsste diese aber seperat anzeigen, damit diese nicht unter gehen meiner Meinung nach.

**Comment by Catzenjaeger** [comment]
kann man ja auch unter visiblity regeln :) 
sorry für Panikmache :)
