### ISSUE TITLE
Error: Page Nav geht nicht --> Illegal string offset 'page_nav'

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#92]
Das hier ist aus der figure.php - eventuell ist hier das Problem	
ich weiss nicht was "Illegal string offset 'page_nav'" bedeutet

```
// Set Empty Arrays
		$info = array("figure_rows" => 0, "page_nav" => false);
		$info['item'] = array();
```

**Fehlermeldungen:**  ```
templates/template_render_figure.php
/test/infusions/figurelib/figures.php?figure_cat_id=2&figure_manufacturer=75
Illegal string offset 'page_nav'
Line: 269
```

Line 269 in besagter Datei wäre die hier: `echo $info['page_nav'] ? "<div class='text-right'>".$info['page_nav']."</div>" : '';`

**Comment by DavidGuetl** [comment]
Sieht so aus als ob die Fehlermeldung bereits entfernt ist, oder?

**Comment by Catzenjaeger** [comment]
nein der Fehler bringt mich um .. die page nav geht definitiv nicht .. rufe mal http://aliencollectors.com/test/infusions/figurelib/figures.php?figure_cat_id=2&figure_manufacturer=75
auf und versuche dort auf seite 2 zu kommen  ... geht nicht und der fehler erscheint im error log

**Comment by Catzenjaeger** [comment]
also, alle versuche hier was zu finden oder da zu fixen schlugen fehl.
Hier würde ich Dich bitten das du da noch einmal drüber schaust .. kann ich nicht soo viel sein.
Das System an sich läuft sonst momentan ohne Fehler

**Comment by Catzenjaeger** [comment]
obwohl FrederickChan einen fehler gefixt hat gehts immer noch nicht :( damn 
new file is here: https://github.com/Catzenjaeger/FigureLib_4/commit/190fbd139518ca25a00da65c70a45cf33e1c9cd6#diff-260ee766a499fde708f12c8817381788

**Comment by Catzenjaeger** [comment]
$_GET['figure_manufacturer'] WAR DIE LÖSUNG THANX ALL FOR HELP
