### ISSUE TITLE
ERROR: Popup image upload doesent work

### ISSUE THREAD

**Issue by Catzenjaeger** [Catzenjaeger/FigureLib_4#99]
die popups mit den Hinweis Bilder copyright gehen nicht mehr auf.

**Comment by DavidGuetl** [comment]
Liegt an jQuery würde ich sagen.

Wenn du jQuery 3.1.0 hast, dann gehts nicht, die ist bei mir auch fehlerhaft. Einfach eine alte jQuery nehmen.

**Comment by Catzenjaeger** [comment]
File: submit.php + admin_figurelib.php

![1](https://cloud.githubusercontent.com/assets/19621858/18239255/60d07500-7344-11e6-97ad-213a6c1da01c.JPG)
![2](https://cloud.githubusercontent.com/assets/19621858/18239259/64b180e2-7344-11e6-8798-48020d0ae698.JPG)

**on video field it works!!! same popup in image upload dosent work!!!**

**Comment by FrederickChan** [comment]
Image upload pop up is working.

**Comment by Catzenjaeger** [comment]
i have try in this moment (10:51 german time) and see no popup :o: 
http://aliencollectors.com/live/infusions/figurelib/submit.php?stype=f

**Comment by Catzenjaeger** [comment]
ups i see my mistake - site and not live
